/**
 * PageSpaceClient facade (Phase 2 task 6) — the last Phase 2 abstraction,
 * composing tasks 2-5 into one invoke pipeline:
 *
 *   validate input (zod) -> buildRequest -> attach Bearer from
 *   auth.getAccessToken() -> executeRequest -> parseResponse -> classified
 *   result.
 *
 * The pipeline itself is a pure composition; `executeRequest` (task 3) is
 * the only step that touches the network, and `auth.getAccessToken()` is the
 * only other I/O edge. Everything else — retry policy, idempotency, the
 * version handshake — is plain data flowing through pure functions
 * (`computeBackoff`, `checkServerCompatibility`) with `fetch`, the clock
 * (`setTimeout`), and randomness (`jitter`) injected at construction.
 *
 * Registry note: `Operation.name` (registry/define.ts) is deliberately typed
 * as `string`, not a per-operation literal, so the registry cannot key a
 * type-safe namespace map on its own. `client.drives.list(...)` is instead
 * generated by walking a fixed namespace -> method -> Operation map
 * (`DEFAULT_OPERATIONS_MAP`) at construction — every leaf is the same
 * generated closure over `#invoke`, never a hand-written wrapper. Callers
 * needing an operation outside that map (Phase 3 growing the registry,
 * or a caller-supplied one-off) use the fully-typed `invoke(op, input)`
 * escape hatch directly, which preserves each operation's own
 * input/output schema types regardless of its name.
 */
import type { z } from 'zod';
import {
  IncompatibleServerError,
  isAuthenticationError,
  isNetworkError,
  isPageSpaceError,
  isRateLimitError,
  isServerError,
  isTimeoutError,
  ValidationError,
  type ValidationIssue,
} from './errors.js';
import type { AuthProvider } from './auth/provider.js';
import { listDrives } from './operations/drives.js';
import { readPage } from './operations/pages.js';
import {
  createTask,
  createTaskStatus,
  deleteTask,
  deleteTaskTrigger,
  getAssignedTasks,
  reorderTask,
  setTaskTrigger,
  updateTask,
} from './operations/tasks.js';
import type { Operation } from './registry/define.js';
import { createRegistry, type OperationRegistry } from './registry/registry.js';
import { buildRequest } from './transport/build-request.js';
import { executeRequest } from './transport/execute.js';
import { parseResponse } from './transport/parse-response.js';
import type { ClientConfig } from './transport/types.js';
import { computeBackoff, DEFAULT_RETRY_POLICY, isIdempotentMethod, type Jitter, type RetryPolicy } from './retry.js';
import { checkServerCompatibility, MIN_SERVER_API_VERSION } from './version.js';

const DEFAULT_OPERATIONS_MAP = {
  drives: { list: listDrives },
  pages: { read: readPage },
  tasks: {
    create: createTask,
    update: updateTask,
    delete: deleteTask,
    reorder: reorderTask,
    createStatus: createTaskStatus,
    setTrigger: setTaskTrigger,
    deleteTrigger: deleteTaskTrigger,
    getAssigned: getAssignedTasks,
  },
} as const;

type OperationsMap = Record<string, Record<string, Operation>>;

/** Mechanically generated from `DEFAULT_OPERATIONS_MAP`: one method per leaf operation, no hand-written wrappers. */
export type ClientNamespaces = {
  readonly [NS in keyof typeof DEFAULT_OPERATIONS_MAP]: {
    readonly [TMethod in keyof (typeof DEFAULT_OPERATIONS_MAP)[NS]]: (typeof DEFAULT_OPERATIONS_MAP)[NS][TMethod] extends Operation<
      string,
      infer TInputSchema,
      infer TOutputSchema
    >
      ? (input: z.infer<TInputSchema>) => Promise<z.infer<TOutputSchema>>
      : never;
  };
};

export interface PageSpaceClientOptions {
  readonly baseUrl: string;
  readonly auth: AuthProvider;
  /** Defaults to the global `fetch`. Injected so tests never touch the network. */
  readonly fetch?: typeof fetch;
  /** Defaults to 30s. */
  readonly timeoutMs?: number;
  readonly retryPolicy?: Partial<RetryPolicy>;
  /** Overrides the request's X-PageSpace-API-Version header; defaults to MIN_SERVER_API_VERSION. */
  readonly apiVersion?: string;
  /** Fail-closed by default (ADR 0001 D4); the only sanctioned opt-out. */
  readonly skipVersionCheck?: boolean;
  /** Defaults to `Math.random`. Injected so backoff delays are deterministic under test. */
  readonly jitter?: Jitter;
  readonly abortFactory?: () => AbortController;
}

function toValidationIssues(issues: ReadonlyArray<{ path: PropertyKey[]; message: string }>): ValidationIssue[] {
  return issues.map((issue) => ({
    path: issue.path.filter((segment): segment is string | number => typeof segment === 'string' || typeof segment === 'number'),
    message: issue.message,
  }));
}

function delay(ms: number): Promise<void> {
  if (ms <= 0) return Promise.resolve();
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function flattenOperations(map: OperationsMap): Operation[] {
  return Object.values(map).flatMap((methods) => Object.values(methods));
}

function buildNamespaces(
  map: OperationsMap,
  invoke: (op: Operation, input: unknown) => Promise<unknown>,
): ClientNamespaces {
  const namespaces: Record<string, Record<string, (input: unknown) => Promise<unknown>>> = {};
  for (const [namespace, methods] of Object.entries(map)) {
    const bucket: Record<string, (input: unknown) => Promise<unknown>> = {};
    for (const [methodName, op] of Object.entries(methods)) {
      bucket[methodName] = (input: unknown) => invoke(op, input);
    }
    namespaces[namespace] = bucket;
  }
  return namespaces as unknown as ClientNamespaces;
}

export interface PageSpaceClient extends ClientNamespaces {}

export class PageSpaceClient {
  readonly #config: ClientConfig;
  readonly #auth: AuthProvider;
  readonly #fetch: typeof fetch;
  readonly #timeoutMs: number;
  readonly #retryPolicy: RetryPolicy;
  readonly #registry: OperationRegistry;
  readonly #skipVersionCheck: boolean;
  readonly #jitter: Jitter;
  readonly #abortFactory: () => AbortController;
  #compatibilityVerified = false;

  constructor(options: PageSpaceClientOptions) {
    this.#config = { baseUrl: options.baseUrl, apiVersion: options.apiVersion };
    this.#auth = options.auth;
    this.#fetch = options.fetch ?? fetch;
    this.#timeoutMs = options.timeoutMs ?? 30_000;
    this.#retryPolicy = { ...DEFAULT_RETRY_POLICY, ...options.retryPolicy };
    this.#skipVersionCheck = options.skipVersionCheck ?? false;
    this.#jitter = options.jitter ?? Math.random;
    this.#abortFactory = options.abortFactory ?? (() => new AbortController());

    this.#registry = createRegistry(flattenOperations(DEFAULT_OPERATIONS_MAP));
    Object.assign(this, buildNamespaces(DEFAULT_OPERATIONS_MAP, (op, input) => this.#invoke(op, input)));
  }

  /**
   * The typed escape hatch every generated namespace method delegates to.
   * Accepts any `Operation` value directly — Phase 3's growing registry and
   * one-off/test operations both flow through the same pipeline without
   * needing to be part of `DEFAULT_OPERATIONS_MAP`.
   */
  async invoke<TInputSchema extends z.ZodType, TOutputSchema extends z.ZodType>(
    op: Operation<string, TInputSchema, TOutputSchema>,
    input: z.infer<TInputSchema>,
  ): Promise<z.infer<TOutputSchema>> {
    return this.#invoke(op, input) as Promise<z.infer<TOutputSchema>>;
  }

  async #invoke(op: Operation, rawInput: unknown): Promise<unknown> {
    const parsedInput = op.inputSchema.safeParse(rawInput);
    if (!parsedInput.success) {
      throw new ValidationError(
        `Invalid input for operation "${op.name}"`,
        toValidationIssues(parsedInput.error.issues),
        op.name,
      );
    }
    // Operation input schemas are always object schemas (path/query/body
    // fields) by registry convention; the generic `Operation` type widens
    // z.infer to `unknown` because TInputSchema isn't known here.
    const input = parsedInput.data as Readonly<Record<string, unknown>>;

    const idempotent = isIdempotentMethod(op.method);
    let retryAttempt = 0;
    let usedAuthRetry = false;

    for (;;) {
      let raw;
      try {
        const token = await this.#auth.getAccessToken();
        const descriptor = buildRequest(op, input, this.#config);
        raw = await executeRequest(
          { ...descriptor, headers: { ...descriptor.headers, Authorization: `Bearer ${token}` } },
          { fetch: this.#fetch, timeoutMs: this.#timeoutMs, abortFactory: this.#abortFactory },
        );
      } catch (error) {
        if (idempotent && (isNetworkError(error) || isTimeoutError(error)) && retryAttempt < this.#retryPolicy.maxRetries) {
          retryAttempt += 1;
          await delay(computeBackoff(retryAttempt, this.#retryPolicy, this.#jitter));
          continue;
        }
        throw error;
      }

      if (!this.#skipVersionCheck && !this.#compatibilityVerified && raw.status >= 200 && raw.status <= 299) {
        const compatibility = checkServerCompatibility(
          raw.headers.get('X-PageSpace-API-Version'),
          MIN_SERVER_API_VERSION,
        );
        if (!compatibility.ok) {
          throw new IncompatibleServerError(compatibility);
        }
        this.#compatibilityVerified = true;
      }

      const parsed = parseResponse(op, raw.status, raw.headers, raw.bodyText);
      if (!isPageSpaceError(parsed)) {
        return parsed;
      }

      if (isAuthenticationError(parsed) && !usedAuthRetry) {
        usedAuthRetry = true;
        this.#auth.invalidate();
        continue;
      }

      if (idempotent && retryAttempt < this.#retryPolicy.maxRetries) {
        if (isRateLimitError(parsed)) {
          retryAttempt += 1;
          const scheduled = computeBackoff(retryAttempt, this.#retryPolicy, this.#jitter);
          const waitMs = parsed.retryAfterMs === null ? scheduled : Math.min(parsed.retryAfterMs, this.#retryPolicy.maxDelayMs);
          await delay(waitMs);
          continue;
        }
        if (isServerError(parsed)) {
          retryAttempt += 1;
          await delay(computeBackoff(retryAttempt, this.#retryPolicy, this.#jitter));
          continue;
        }
      }

      throw parsed;
    }
  }
}
