/**
 * WebSocket Payload Validation
 *
 * Pure functions for validating socket event payloads.
 * Following Eric Elliott's functional programming principles:
 * - Pure predicates (no side effects)
 * - Composed validators
 * - Result types instead of exceptions
 */

// CUID2 format: lowercase alphanumeric, typically 24 characters (min 2, max 32)
// Generated by @paralleldrive/cuid2 which PageSpace uses for all IDs
// Pattern: starts with a letter, followed by lowercase alphanumeric
const CUID2_REGEX = /^[a-z][a-z0-9]{1,31}$/;

// Max length check before regex to prevent ReDoS
const MAX_CUID2_LENGTH = 32;

/**
 * Result type for validation - avoids exceptions, explicit success/failure
 */
export type ValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: string };

/**
 * Type guard: checks if input is a valid CUID2 string
 * CUID2 is generated by @paralleldrive/cuid2 (PageSpace's ID format)
 * Pure predicate - no side effects
 */
export const isCUID2 = (input: unknown): input is string => {
  if (typeof input !== 'string') return false;
  if (input.length > MAX_CUID2_LENGTH) return false;
  if (input.length < 2) return false;
  return CUID2_REGEX.test(input);
};

/**
 * Higher-order function: creates a length validator
 * Pure - returns a predicate function
 */
export const isNotTooLong =
  (max: number) =>
  (input: string): boolean =>
    input.length <= max;

/**
 * Validates a page ID payload
 * Returns Result type - never throws
 */
export const validatePageId = (input: unknown): ValidationResult<string> => {
  if (typeof input !== 'string') {
    return { ok: false, error: 'Page ID must be a string' };
  }
  if (!isCUID2(input)) {
    return { ok: false, error: 'invalid Page ID format' };
  }
  return { ok: true, value: input };
};

/**
 * Validates a drive ID payload
 * Returns Result type - never throws
 */
export const validateDriveId = (input: unknown): ValidationResult<string> => {
  if (typeof input !== 'string') {
    return { ok: false, error: 'Drive ID must be a string' };
  }
  if (!isCUID2(input)) {
    return { ok: false, error: 'Drive ID must be a valid ID' };
  }
  return { ok: true, value: input };
};

/**
 * Validates a conversation ID payload
 * Returns Result type - never throws
 */
export const validateConversationId = (input: unknown): ValidationResult<string> => {
  if (typeof input !== 'string') {
    return { ok: false, error: 'Conversation ID must be a string' };
  }
  if (!isCUID2(input)) {
    return { ok: false, error: 'Conversation ID must be a valid ID' };
  }
  return { ok: true, value: input };
};

/**
 * Socket type for validation error emission
 */
interface SocketLike {
  emit: (event: string, data: unknown) => void;
}

/**
 * Emits a validation error to the client
 * Side effect function - kept separate from pure validation logic
 */
export const emitValidationError = (
  socket: SocketLike,
  event: string,
  error: string
): void => {
  socket.emit('validation_error', { event, error });
};
