'use client';

import { createContext, useContext, ReactNode } from 'react';

/**
 * Threads the per-request CSP nonce (generated by middleware, read server-side
 * in `dashboard/layout.tsx`) down to client components that need to stamp it
 * onto content they render — e.g. `CanvasFrame`, whose `srcDoc` iframe inherits
 * the app shell's nonce-based CSP and must match it on author `<script>` tags.
 * Context (not props) so components in between that don't care about the
 * nonce (`CanvasPageView`, `CenterPanel`) don't need to touch their signatures.
 */
const NonceContext = createContext<string | undefined>(undefined);

export function NonceProvider({ nonce, children }: { nonce: string | undefined; children?: ReactNode }) {
  return <NonceContext.Provider value={nonce}>{children}</NonceContext.Provider>;
}

export function useNonce(): string | undefined {
  return useContext(NonceContext);
}
