/**
 * Pure functions for the quality gate (scripts/quality/quality-gate.mjs).
 *
 * Everything here is deterministic data-in/data-out — no fs, no process, no
 * ESLint. The imperative shell in quality-gate.mjs owns all I/O. Tested in
 * scripts/__tests__/quality-gate.test.ts.
 */

/** Pseudo-rule tracked alongside real ESLint rules: count of eslint-disable
 * directives in a file. New suppressions ratchet exactly like new violations —
 * silencing a rule shows up in the baseline diff just as loudly as breaking it. */
export const SUPPRESSION_RULE = 'quality/eslint-disable-directive';

/**
 * Count eslint-disable directives (line, next-line, and block form) in a
 * source text. Matches inside strings are theoretically possible but have the
 * same cost as a real directive for review purposes, so no attempt is made to
 * parse them out.
 */
export function countSuppressions(sourceText) {
  const matches = sourceText.match(/eslint-disable(?:-next-line|-line)?/g);
  return matches ? matches.length : 0;
}

/**
 * Fold ESLint results plus per-file suppression counts into the canonical
 * shape: { [relativePath]: { [ruleId]: count } }. Files with zero findings are
 * omitted entirely so the baseline only lists debt, not the whole tree.
 *
 * @param results  Array of { filePath, messages: [{ ruleId }] } (ESLint shape).
 * @param suppressionsByFile  { [filePath]: directiveCount } keyed the same way.
 * @param toRelative  filePath -> repo-relative posix path.
 */
export function countByFileAndRule(results, suppressionsByFile, toRelative) {
  const files = {};
  const bump = (file, rule) => {
    const rel = toRelative(file);
    files[rel] = files[rel] ?? {};
    files[rel][rule] = (files[rel][rule] ?? 0) + 1;
  };
  for (const result of results) {
    for (const message of result.messages) {
      // ruleId is null for parse errors — track them under a stable name so a
      // file the gate cannot parse is a regression, not an invisible skip.
      bump(result.filePath, message.ruleId ?? 'quality/parse-error');
    }
  }
  for (const [filePath, count] of Object.entries(suppressionsByFile)) {
    for (let i = 0; i < count; i++) bump(filePath, SUPPRESSION_RULE);
  }
  return files;
}

/** Sum a files map into { [ruleId]: total }. */
export function ruleTotals(files) {
  const totals = {};
  for (const rules of Object.values(files)) {
    for (const [rule, count] of Object.entries(rules)) {
      totals[rule] = (totals[rule] ?? 0) + count;
    }
  }
  return totals;
}

/**
 * Compare current state to the committed baseline.
 *
 * A regression is any (file, rule) cell whose current count exceeds its
 * baseline count — including files or rules the baseline has never seen.
 * Per-cell granularity is deliberate: fixing three `any`s in one file never
 * buys headroom to add one in another.
 *
 * An improvement is any cell whose current count is below baseline (deleted
 * files count too). Improvements never fail the gate; they mean the baseline
 * can be re-locked lower via --update.
 */
export function diffAgainstBaseline(baselineFiles, currentFiles) {
  const regressions = [];
  const improvements = [];
  const allFiles = new Set([...Object.keys(baselineFiles), ...Object.keys(currentFiles)]);
  for (const file of [...allFiles].sort()) {
    const before = baselineFiles[file] ?? {};
    const after = currentFiles[file] ?? {};
    const allRules = new Set([...Object.keys(before), ...Object.keys(after)]);
    for (const rule of [...allRules].sort()) {
      const b = before[rule] ?? 0;
      const a = after[rule] ?? 0;
      if (a > b) regressions.push({ file, rule, baseline: b, current: a });
      else if (a < b) improvements.push({ file, rule, baseline: b, current: a });
    }
  }
  return { regressions, improvements };
}

/** Recursively sort object keys so baseline JSON diffs are stable. */
function sortKeys(value) {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return value;
  return Object.fromEntries(
    Object.keys(value)
      .sort()
      .map((k) => [k, sortKeys(value[k])]),
  );
}

/**
 * Serialize a files map into the committed baseline document. Deterministic:
 * same input state always yields byte-identical output, so `git diff
 * quality-baseline.json` is a faithful record of debt movement and nothing else.
 */
export function serializeBaseline(files) {
  const doc = {
    '//': 'Quality debt baseline. Generated by `bun run quality:update` — do not edit by hand. Counts may only go down; CI fails on any increase. See docs/QUALITY.md.',
    totals: sortKeys(ruleTotals(files)),
    files: sortKeys(files),
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/** Grand total across all cells of a files map. */
export function grandTotal(files) {
  return Object.values(ruleTotals(files)).reduce((sum, n) => sum + n, 0);
}

/**
 * Render the human report. Returns an array of lines (the shell joins and
 * prints) so tests can assert on content without capturing stdout.
 */
export function formatReport({ regressions, improvements, baselineFiles, currentFiles }) {
  const lines = [];
  const before = ruleTotals(baselineFiles);
  const after = ruleTotals(currentFiles);
  const allRules = [...new Set([...Object.keys(before), ...Object.keys(after)])].sort();

  lines.push('Rule totals (baseline -> current):');
  for (const rule of allRules) {
    const b = before[rule] ?? 0;
    const a = after[rule] ?? 0;
    const marker = a > b ? '  << REGRESSION' : a < b ? '  (improved)' : '';
    lines.push(`  ${rule.padEnd(42)} ${String(b).padStart(5)} -> ${String(a).padStart(5)}${marker}`);
  }
  lines.push(`  ${'TOTAL'.padEnd(42)} ${String(grandTotal(baselineFiles)).padStart(5)} -> ${String(grandTotal(currentFiles)).padStart(5)}`);

  if (regressions.length > 0) {
    lines.push('');
    lines.push(`FAIL: ${regressions.length} regression(s) against quality-baseline.json:`);
    for (const r of regressions) {
      lines.push(`  ${r.file}`);
      lines.push(`    ${r.rule}: ${r.baseline} -> ${r.current}`);
    }
    lines.push('');
    lines.push('Fix the new violation(s), or — only if a violation is genuinely justified —');
    lines.push('run `bun run quality:update` and commit the baseline change so the exception');
    lines.push('is visible in review.');
  }

  if (improvements.length > 0 && regressions.length === 0) {
    lines.push('');
    lines.push(`${improvements.length} cell(s) improved below baseline. Run \`bun run quality:update\` to lock in the gains.`);
  }

  return lines;
}
