import { db, workflows, pages, eq, and } from '@pagespace/db';
import type { EventTrigger } from '@pagespace/db';
import { executeWorkflow } from './workflow-executor';
import { loggers } from '@pagespace/lib/server';

export interface WorkflowEvent {
  operation: string;
  resourceType: string;
  resourceId: string;
  driveId: string | null;
  pageId: string | null;
  userId: string;
  isAiGenerated?: boolean;
  aiConversationId?: string | null;
  metadata?: Record<string, unknown>;
}

// In-memory debounce buffer: workflowId -> timeout handle
// NOTE: These Maps are process-local. In a multi-instance deployment, events
// hitting different instances won't debounce against each other. Acceptable for
// single-instance Docker; move to Redis if horizontal scaling is needed.
const debounceTimers = new Map<string, ReturnType<typeof setTimeout>>();

// Track pending event context per workflow for injection into the prompt
const pendingEventContexts = new Map<string, string>();

/**
 * Called from the activity logger hook. Finds matching event-triggered
 * workflows and executes them (debounced).
 */
export async function emitWorkflowEvent(event: WorkflowEvent): Promise<void> {
  // Skip if no driveId - event-triggered workflows are scoped to drives
  if (!event.driveId) return;

  // Recursive trigger prevention: skip if event was generated by a workflow
  if (event.isAiGenerated && event.aiConversationId?.startsWith('workflow-')) {
    return;
  }

  try {
    // Find enabled event-triggered workflows in this drive
    const matchingWorkflows = await db
      .select()
      .from(workflows)
      .where(
        and(
          eq(workflows.isEnabled, true),
          eq(workflows.triggerType, 'event'),
          eq(workflows.driveId, event.driveId)
        )
      );

    if (matchingWorkflows.length === 0) return;

    for (const workflow of matchingWorkflows) {
      const eventTriggers = (workflow.eventTriggers as EventTrigger[] | null) ?? [];

      // Check if any trigger matches this event
      const matches = eventTriggers.some(
        trigger => trigger.operation === event.operation && trigger.resourceType === event.resourceType
      );
      if (!matches) continue;

      // Check folder scoping
      const watchedFolderIds = (workflow.watchedFolderIds as string[] | null) ?? [];
      if (watchedFolderIds.length > 0) {
        // The event's pageId is the parent folder. If the resource IS a page,
        // we need to check its parentId as well.
        let folderMatch = false;

        if (event.pageId && watchedFolderIds.includes(event.pageId)) {
          folderMatch = true;
        }

        // Also check if the resource itself is inside a watched folder
        if (!folderMatch && event.resourceId) {
          try {
            const [resource] = await db
              .select({ parentId: pages.parentId })
              .from(pages)
              .where(eq(pages.id, event.resourceId));

            if (resource?.parentId && watchedFolderIds.includes(resource.parentId)) {
              folderMatch = true;
            }
          } catch {
            // Resource might not be a page (could be a file, member, etc.)
          }
        }

        if (!folderMatch) continue;
      }

      // Build event context string for prompt injection
      const contextStr = buildEventContext(event);

      // Apply debounce
      const debounceSecs = workflow.eventDebounceSecs ?? 30;
      const existingTimer = debounceTimers.get(workflow.id);

      if (existingTimer) {
        // Update pending context (latest event info)
        pendingEventContexts.set(workflow.id, contextStr);
        // Timer already running - events are coalescing
        continue;
      }

      // Store context and set debounce timer
      pendingEventContexts.set(workflow.id, contextStr);

      const timer = setTimeout(() => {
        void (async () => {
          try {
            debounceTimers.delete(workflow.id);
            const eventContext = pendingEventContexts.get(workflow.id);
            pendingEventContexts.delete(workflow.id);

            // Re-validate: workflow may have been disabled or deleted during debounce
            const [current] = await db
              .select()
              .from(workflows)
              .where(eq(workflows.id, workflow.id));

            if (!current || !current.isEnabled) return;

            // Skip if trigger type was changed away from event during debounce
            if (current.triggerType !== 'event') return;

            // Skip if another execution is already in progress
            if (current.lastRunStatus === 'running') return;

            await executeEventWorkflow(current, eventContext ?? contextStr);
          } catch (error) {
            loggers.api.error('Error in debounced workflow execution', {
              workflowId: workflow.id,
              error: error instanceof Error ? error.message : String(error),
            });
          }
        })();
      }, debounceSecs * 1000);

      debounceTimers.set(workflow.id, timer);
    }
  } catch (error) {
    loggers.api.error('Error in emitWorkflowEvent', {
      error: error instanceof Error ? error.message : String(error),
      operation: event.operation,
      resourceType: event.resourceType,
      driveId: event.driveId,
    });
  }
}

const maxContextFieldLength = 200;

const truncate = (value: unknown, max = maxContextFieldLength): string => {
  const str = String(value ?? '');
  return str.length > max ? `${str.slice(0, max)}...` : str;
};

function buildEventContext(event: WorkflowEvent): string {
  const parts = [`Event: ${event.operation} on ${event.resourceType}`];
  if (event.resourceId) parts.push(`Resource ID: ${event.resourceId}`);
  if (event.metadata) {
    const title = event.metadata.resourceTitle || event.metadata.title;
    if (title) parts.push(`Name: ${truncate(title)}`);
    const folder = event.metadata.folderName || event.metadata.parentTitle;
    if (folder) parts.push(`Folder: ${truncate(folder)}`);
  }
  return `<event-data>\n${parts.join('\n')}\n</event-data>`;
}

async function executeEventWorkflow(
  workflow: typeof workflows.$inferSelect,
  eventContext: string
): Promise<void> {
  try {
    // Mark as running
    await db
      .update(workflows)
      .set({ lastRunStatus: 'running', lastRunAt: new Date() })
      .where(eq(workflows.id, workflow.id));

    // Inject event context into prompt
    const enhancedWorkflow = {
      ...workflow,
      prompt: `${eventContext}\n\n${workflow.prompt}`,
    };

    const result = await executeWorkflow(enhancedWorkflow);

    // Update status (event workflows don't have nextRunAt from cron)
    await db
      .update(workflows)
      .set({
        lastRunAt: new Date(),
        lastRunStatus: result.success ? 'success' : 'error',
        lastRunError: result.error || null,
        lastRunDurationMs: result.durationMs,
      })
      .where(eq(workflows.id, workflow.id));

    loggers.api.info('Event-triggered workflow executed', {
      workflowId: workflow.id,
      workflowName: workflow.name,
      success: result.success,
      durationMs: result.durationMs,
    });
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    loggers.api.error('Event-triggered workflow failed', {
      workflowId: workflow.id,
      error: errorMsg,
    });

    await db
      .update(workflows)
      .set({
        lastRunStatus: 'error',
        lastRunError: errorMsg,
      })
      .where(eq(workflows.id, workflow.id));
  }
}
