import { describe, it, expect } from 'vitest';
import {
  isValidUserId,
  isValidFilename,
  isValidAvatarExtension,
  resolveAvatarPath,
} from '../safe-path';

describe('Safe Path Utilities - Security Tests', () => {
  // CUID2 format IDs as used throughout the codebase (generated by @paralleldrive/cuid2)
  const VALID_CUID2 = 'clh3am7ho0000ml08f8gth9r0';
  const VALID_CUID2_ALT = 'cm1234567890abcdefghijk';
  const STORAGE_BASE = '/storage';

  describe('isValidUserId', () => {
    it('should accept valid CUID2 identifiers', () => {
      expect(isValidUserId(VALID_CUID2)).toBe(true);
      expect(isValidUserId(VALID_CUID2_ALT)).toBe(true);
      expect(isValidUserId('abc123')).toBe(true);
      expect(isValidUserId('user_id-123')).toBe(true);
    });

    it('should reject identifiers that are too short', () => {
      expect(isValidUserId('ab')).toBe(false);
      expect(isValidUserId('')).toBe(false);
    });

    it('should reject identifiers that are too long', () => {
      expect(isValidUserId('a'.repeat(65))).toBe(false);
    });

    it('should reject path traversal in userId', () => {
      expect(isValidUserId('../..')).toBe(false);
      expect(isValidUserId('..%2F..%2F')).toBe(false);
      expect(isValidUserId('clh3am7ho/../../../etc')).toBe(false);
    });

    it('should reject identifiers with invalid characters', () => {
      expect(isValidUserId('user/id')).toBe(false);
      expect(isValidUserId('user\\id')).toBe(false);
      expect(isValidUserId('user.id')).toBe(false);
      expect(isValidUserId('user@id')).toBe(false);
    });

    it('should reject non-string inputs', () => {
      expect(isValidUserId(null as unknown as string)).toBe(false);
      expect(isValidUserId(undefined as unknown as string)).toBe(false);
      expect(isValidUserId(123 as unknown as string)).toBe(false);
    });
  });

  describe('isValidFilename', () => {
    it('should accept valid filenames', () => {
      expect(isValidFilename('avatar.png')).toBe(true);
      expect(isValidFilename('profile-pic.jpg')).toBe(true);
      expect(isValidFilename('user_photo_123.webp')).toBe(true);
    });

    it('should reject path traversal sequences', () => {
      expect(isValidFilename('../../../etc/passwd')).toBe(false);
      expect(isValidFilename('..%2F..%2F..%2Fetc%2Fpasswd')).toBe(false);
      expect(isValidFilename('../../.env')).toBe(false);
      expect(isValidFilename('foo/../bar.png')).toBe(false);
    });

    it('should reject forward slashes', () => {
      expect(isValidFilename('path/to/file.png')).toBe(false);
      expect(isValidFilename('/etc/passwd')).toBe(false);
    });

    it('should reject backslashes (Windows paths)', () => {
      expect(isValidFilename('path\\to\\file.png')).toBe(false);
      expect(isValidFilename('..\\..\\secret.txt')).toBe(false);
    });

    it('should reject very long filenames (DoS prevention)', () => {
      const longFilename = 'a'.repeat(300) + '.png';
      expect(isValidFilename(longFilename)).toBe(false);
    });

    it('should reject empty filenames', () => {
      expect(isValidFilename('')).toBe(false);
    });

    it('should reject filenames starting with special characters', () => {
      expect(isValidFilename('.hidden.png')).toBe(false);
      expect(isValidFilename('-dash.png')).toBe(false);
      expect(isValidFilename('_underscore.png')).toBe(false);
    });

    it('should reject filenames without extensions', () => {
      expect(isValidFilename('noextension')).toBe(false);
    });

    it('should reject double dots in filename', () => {
      expect(isValidFilename('file..png')).toBe(false);
      expect(isValidFilename('..png')).toBe(false);
    });
  });

  describe('isValidAvatarExtension', () => {
    it('should accept allowed image extensions', () => {
      expect(isValidAvatarExtension('photo.jpg')).toBe(true);
      expect(isValidAvatarExtension('photo.jpeg')).toBe(true);
      expect(isValidAvatarExtension('photo.png')).toBe(true);
      expect(isValidAvatarExtension('photo.gif')).toBe(true);
      expect(isValidAvatarExtension('photo.webp')).toBe(true);
    });

    it('should accept extensions case-insensitively', () => {
      expect(isValidAvatarExtension('photo.PNG')).toBe(true);
      expect(isValidAvatarExtension('photo.JPG')).toBe(true);
      expect(isValidAvatarExtension('photo.WEBP')).toBe(true);
    });

    it('should reject disallowed extensions', () => {
      expect(isValidAvatarExtension('script.js')).toBe(false);
      expect(isValidAvatarExtension('page.html')).toBe(false);
      expect(isValidAvatarExtension('data.json')).toBe(false);
      expect(isValidAvatarExtension('file.exe')).toBe(false);
      expect(isValidAvatarExtension('config.env')).toBe(false);
      expect(isValidAvatarExtension('shell.sh')).toBe(false);
    });
  });

  describe('resolveAvatarPath', () => {
    describe('valid inputs', () => {
      it('should resolve valid avatar paths', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, 'avatar.png');
        expect(result.success).toBe(true);
        if (result.success) {
          expect(result.path).toContain('avatars');
          expect(result.path).toContain(VALID_CUID2);
          expect(result.path).toContain('avatar.png');
        }
      });
    });

    describe('path traversal attacks', () => {
      it('should reject ../../../etc/passwd', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '../../../etc/passwd');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_filename');
        }
      });

      it('should reject ../../.env', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '../../.env');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_filename');
        }
      });

      it('should reject URL-encoded traversal ..%2F..%2F.env', () => {
        // Note: Next.js decodes URL params, so this tests the decoded version
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '../..%2F.env');
        expect(result.success).toBe(false);
      });

      it('should reject double-encoded traversal', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '%252e%252e%252f.env');
        expect(result.success).toBe(false);
      });

      it('should reject backslash traversal (Windows)', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '..\\..\\secret.txt');
        expect(result.success).toBe(false);
      });

      it('should reject userId with path traversal', () => {
        const result = resolveAvatarPath(STORAGE_BASE, '../../../etc', 'passwd');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_user_id');
        }
      });

      it('should reject userId combined with filename traversal', () => {
        const result = resolveAvatarPath(STORAGE_BASE, '..', '../.env');
        expect(result.success).toBe(false);
      });
    });

    describe('invalid user ID', () => {
      it('should reject userId with invalid characters', () => {
        const result = resolveAvatarPath(STORAGE_BASE, 'user/with/slashes', 'avatar.png');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_user_id');
        }
      });

      it('should reject empty userId', () => {
        const result = resolveAvatarPath(STORAGE_BASE, '', 'avatar.png');
        expect(result.success).toBe(false);
      });

      it('should reject userId that is too short', () => {
        const result = resolveAvatarPath(STORAGE_BASE, 'ab', 'avatar.png');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_user_id');
        }
      });

      it('should reject userId that is too long', () => {
        const result = resolveAvatarPath(STORAGE_BASE, 'a'.repeat(65), 'avatar.png');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_user_id');
        }
      });
    });

    describe('invalid filename', () => {
      it('should reject empty filename', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_filename');
        }
      });

      it('should reject very long filename', () => {
        const longName = 'a'.repeat(300) + '.png';
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, longName);
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_filename');
        }
      });

      it('should reject filename with invalid characters', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, 'file<script>.png');
        expect(result.success).toBe(false);
      });
    });

    describe('invalid extension', () => {
      it('should reject non-image extensions', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, 'script.js');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.error).toBe('invalid_extension');
        }
      });

      it('should reject .env files', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, 'config.env');
        expect(result.success).toBe(false);
      });

      it('should reject executable files', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, 'malware.exe');
        expect(result.success).toBe(false);
      });
    });

    describe('error messages do not leak information', () => {
      it('should not include file paths in error messages', () => {
        const result = resolveAvatarPath(STORAGE_BASE, VALID_CUID2, '../../../etc/passwd');
        expect(result.success).toBe(false);
        if (!result.success) {
          expect(result.message).not.toContain(STORAGE_BASE);
          expect(result.message).not.toContain('etc');
          expect(result.message).not.toContain('passwd');
        }
      });
    });
  });
});
