/**
 * Drift guard for the SDK's PKCE copy (`../pkce.ts`), deliberately copied
 * (not imported) from `packages/lib/src/auth/oauth/pkce.ts` so the published
 * SDK never runtime-imports `@pagespace/lib` (see `../pkce.ts`'s module doc,
 * and the same pattern in `../client.test.ts` for `PAGESPACE_CLI_CLIENT_ID`
 * and `../../operations/__tests__/roles-pageperm-drift-guard.test.ts` for
 * `PagePerm`). This test-only import from `@pagespace/lib` (a
 * devDependency, never in the published `dist`) asserts the two copies
 * produce byte-for-byte identical output for the same input.
 *
 * `deriveCodeChallenge` has identical signatures and behavior on both sides
 * (pure SHA256/base64url, no bounds), so it is compared directly across
 * several inputs. `generateCodeVerifier` is compared only across the
 * SDK's own valid 32-96 byte range: the SDK's copy additionally validates
 * that range (added because it is public SDK surface external callers can
 * misuse — see `../pkce.ts` module doc), while the provider-side original
 * has no such guard (it only ever receives internally-generated byte
 * counts). That is a deliberate, one-way hardening on top of the same
 * shared core algorithm, not accidental drift — asserted explicitly below
 * rather than left as an untested discrepancy.
 */
import { describe, expect, it } from 'vitest';
import {
  deriveCodeChallenge as libDeriveCodeChallenge,
  generateCodeVerifier as libGenerateCodeVerifier,
} from '@pagespace/lib/auth/oauth/pkce';
import { deriveCodeChallenge, generateCodeVerifier } from '../pkce.js';

describe('deriveCodeChallenge — drift guard vs @pagespace/lib canonical implementation', () => {
  it('produces byte-for-byte identical output for a range of verifier strings', () => {
    const verifiers = [
      'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
      'a',
      'A'.repeat(128),
      'mixed-Case_and-Digits012789',
    ];
    for (const verifier of verifiers) {
      expect(deriveCodeChallenge(verifier)).toBe(libDeriveCodeChallenge(verifier));
    }
  });
});

describe('generateCodeVerifier — drift guard vs @pagespace/lib canonical implementation', () => {
  it('produces byte-for-byte identical output across the SDK\'s valid 32-96 byte range', () => {
    for (const n of [32, 48, 64, 80, 96]) {
      const bytes = new Uint8Array(n).map((_, i) => i % 256);
      expect(generateCodeVerifier(bytes)).toBe(libGenerateCodeVerifier(bytes));
    }
  });

  it('documents the one deliberate divergence: the SDK copy bounds-checks; the lib original does not', () => {
    const tooFew = new Uint8Array(8);
    expect(() => generateCodeVerifier(tooFew)).toThrow(RangeError);
    expect(() => libGenerateCodeVerifier(tooFew)).not.toThrow();
  });
});
