/**
 * Broadcast Audience Authorization Tests (#972)
 *
 * GDPR Art 5(1)(c) minimization + Art 32: the /api/broadcast HTTP endpoint
 * authenticates the SENDER via HMAC, but must also constrain the AUDIENCE
 * (the channelId / Socket.IO room it emits to) so a valid signature cannot
 * be replayed/forged to fan a payload out to an arbitrary or malformed room.
 *
 * authorizeBroadcastAudience is a PURE, deterministic structural validator.
 * It accepts only channelId shapes that the realtime server actually joins
 * sockets into (see src/index.ts socket.join(...) calls), rejecting everything
 * else even when the request is correctly signed.
 */

import { describe, it, expect } from 'vitest';
import { authorizeBroadcastAudience } from '../broadcast-audience';

// Sample valid CUID2 IDs (generated by @paralleldrive/cuid2)
const CUID_A = 'athmieqpwr4ax1t2e0i4lmor';
const CUID_B = 's8y6ofv16t5ya72d7qiq0ex8';

describe('authorizeBroadcastAudience', () => {
  describe('given a well-formed broadcast with an allowed room shape', () => {
    const allowedChannelIds = [
      CUID_A, // bare pageId (page/channel room)
      `notifications:${CUID_A}`,
      `user:${CUID_A}:tasks`,
      `user:${CUID_A}:calendar`,
      `user:${CUID_A}:drives`,
      `user:${CUID_A}:global`,
      `drive:${CUID_A}`,
      `drive:${CUID_A}:calendar`,
      `dm:${CUID_A}`,
      `activity:drive:${CUID_A}`,
      `activity:page:${CUID_A}`,
    ];

    for (const channelId of allowedChannelIds) {
      it(`should allow channelId "${channelId}"`, () => {
        const result = authorizeBroadcastAudience({
          channelId,
          event: 'new_message',
          payload: { foo: 'bar' },
        });
        expect(result.allowed).toBe(true);
        expect(result.reason).toBeUndefined();
      });
    }
  });

  describe('given a missing or empty channelId', () => {
    it('should reject an empty-string channelId', () => {
      const result = authorizeBroadcastAudience({
        channelId: '',
        event: 'new_message',
        payload: {},
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });

    it('should reject an undefined channelId', () => {
      const result = authorizeBroadcastAudience({
        channelId: undefined as unknown as string,
        event: 'new_message',
        payload: {},
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });

    it('should reject a non-string channelId', () => {
      const result = authorizeBroadcastAudience({
        channelId: 123 as unknown as string,
        event: 'new_message',
        payload: {},
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });
  });

  describe('given a missing or invalid event', () => {
    it('should reject a non-string event', () => {
      const result = authorizeBroadcastAudience({
        channelId: CUID_A,
        event: 42 as unknown as string,
        payload: {},
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });

    it('should reject an empty-string event', () => {
      const result = authorizeBroadcastAudience({
        channelId: CUID_A,
        event: '',
        payload: {},
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });
  });

  describe('given a missing payload', () => {
    it('should reject an undefined payload', () => {
      const result = authorizeBroadcastAudience({
        channelId: CUID_A,
        event: 'new_message',
        payload: undefined,
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });

    it('should reject a null payload', () => {
      const result = authorizeBroadcastAudience({
        channelId: CUID_A,
        event: 'new_message',
        payload: null,
      });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBeTruthy();
    });
  });

  describe('given a channelId that matches no legitimate room shape', () => {
    const disallowedChannelIds = [
      'EVERYONE',
      '*',
      'drive:*',
      'random-prefix:abc',
      `unknown:${CUID_A}`,
      `user:${CUID_A}:secrets`, // unknown user suffix
      `user:${CUID_A}`, // user prefix without a known suffix
      `drive:${CUID_A}:secrets`, // unknown drive suffix
      `activity:${CUID_A}`, // activity without page:/drive:
      `activity:thing:${CUID_A}`, // unknown activity scope
      'notifications:', // missing id
      'notifications:NOT_A_CUID', // uppercase invalid id segment
      `notifications:${CUID_A}:extra`, // trailing segment
      'NOTACUID', // bare but not a CUID2
      `${CUID_A} ${CUID_B}`, // injection-ish multi-room
    ];

    for (const channelId of disallowedChannelIds) {
      it(`should reject channelId "${channelId}"`, () => {
        const result = authorizeBroadcastAudience({
          channelId,
          event: 'new_message',
          payload: {},
        });
        expect(result.allowed).toBe(false);
        expect(result.reason).toBeTruthy();
      });
    }
  });

  describe('purity / referential transparency', () => {
    it('should return equal results for equal inputs (no hidden state)', () => {
      const input = { channelId: `drive:${CUID_A}`, event: 'x', payload: { a: 1 } };
      const first = authorizeBroadcastAudience(input);
      const second = authorizeBroadcastAudience(input);
      expect(first).toEqual(second);
    });

    it('should not mutate its input', () => {
      const input = { channelId: CUID_A, event: 'x', payload: { a: 1 } };
      const snapshot = JSON.stringify(input);
      authorizeBroadcastAudience(input);
      expect(JSON.stringify(input)).toBe(snapshot);
    });
  });
});
