/**
 * WebSocket Payload Validation Tests
 * TDD-first: Pure functions for validating socket event payloads
 *
 * Following Eric Elliott's approach:
 * - Pure predicates (isCUID2, isNotTooLong)
 * - Composed validators (validatePageId, validateDriveId, etc.)
 * - Result types instead of exceptions
 */

import { describe, it, expect, vi } from 'vitest';
import {
  isCUID2,
  isNotTooLong,
  validatePageId,
  validateDriveId,
  validateConversationId,
  emitValidationError,
  type ValidationResult,
} from '../validation';

// Sample valid CUID2 IDs (generated by @paralleldrive/cuid2)
const VALID_CUID2_1 = 'athmieqpwr4ax1t2e0i4lmor';
const VALID_CUID2_2 = 's8y6ofv16t5ya72d7qiq0ex8';
const VALID_CUID2_3 = 'ub6ojxvdbqcj0v3854ruec3o';

describe('isCUID2', () => {
  describe('given valid CUID2 strings', () => {
    it('should return true for valid CUID2', () => {
      const result = isCUID2(VALID_CUID2_1);
      expect(result).toBe(true);
    });

    it('should return true for another valid CUID2', () => {
      const result = isCUID2(VALID_CUID2_2);
      expect(result).toBe(true);
    });

    it('should return true for minimum length CUID2 (2 chars)', () => {
      const result = isCUID2('ab');
      expect(result).toBe(true);
    });

    it('should return true for maximum length CUID2 (32 chars)', () => {
      const result = isCUID2('abcdefghij1234567890abcdefghij12');
      expect(result).toBe(true);
    });
  });

  describe('given invalid inputs', () => {
    it('should return false for non-string input (number)', () => {
      const result = isCUID2(12345);
      expect(result).toBe(false);
    });

    it('should return false for non-string input (null)', () => {
      const result = isCUID2(null);
      expect(result).toBe(false);
    });

    it('should return false for non-string input (undefined)', () => {
      const result = isCUID2(undefined);
      expect(result).toBe(false);
    });

    it('should return false for non-string input (object)', () => {
      const result = isCUID2({ id: VALID_CUID2_1 });
      expect(result).toBe(false);
    });

    it('should return false for non-string input (array)', () => {
      const result = isCUID2([VALID_CUID2_1]);
      expect(result).toBe(false);
    });

    it('should return false for empty string', () => {
      const result = isCUID2('');
      expect(result).toBe(false);
    });

    it('should return false for single character (too short)', () => {
      const result = isCUID2('a');
      expect(result).toBe(false);
    });

    it('should return false for string starting with number', () => {
      const result = isCUID2('1abcdefghij1234567890abc');
      expect(result).toBe(false);
    });

    it('should return false for uppercase letters', () => {
      const result = isCUID2('ATHMIEQPWR4AX1T2E0I4LMOR');
      expect(result).toBe(false);
    });

    it('should return false for string with special characters', () => {
      const result = isCUID2('athm-ieqp-wr4a-x1t2');
      expect(result).toBe(false);
    });

    it('should return false for too long string (33 chars)', () => {
      const result = isCUID2('abcdefghij1234567890abcdefghij123');
      expect(result).toBe(false);
    });

    it('should return false for SQL injection attempt', () => {
      const result = isCUID2("'; DROP TABLE pages; --");
      expect(result).toBe(false);
    });

    it('should return false for extremely long string (DoS prevention)', () => {
      const longString = 'a'.repeat(10000);
      const result = isCUID2(longString);
      expect(result).toBe(false);
    });

    it('should return false for UUID format (not CUID2)', () => {
      const result = isCUID2('550e8400-e29b-41d4-a716-446655440000');
      expect(result).toBe(false);
    });
  });
});

describe('isNotTooLong', () => {
  describe('given max length of 32 (CUID2 max length)', () => {
    const checkLength = isNotTooLong(32);

    it('should return true for string at max length', () => {
      const result = checkLength('abcdefghij1234567890abcdefghij12');
      expect(result).toBe(true);
    });

    it('should return true for string under max length', () => {
      const result = checkLength('short');
      expect(result).toBe(true);
    });

    it('should return false for string over max length', () => {
      const result = checkLength('abcdefghij1234567890abcdefghij123');
      expect(result).toBe(false);
    });

    it('should return true for empty string', () => {
      const result = checkLength('');
      expect(result).toBe(true);
    });
  });
});

describe('validatePageId', () => {
  describe('given valid page ID', () => {
    it('should return success with the validated CUID2', () => {
      const result = validatePageId(VALID_CUID2_1);

      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.value).toBe(VALID_CUID2_1);
      }
    });
  });

  describe('given invalid page ID', () => {
    it('should return failure for non-CUID2 string', () => {
      const result = validatePageId('not-a-cuid2');

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error).toContain('invalid');
      }
    });

    it('should return failure for non-string input', () => {
      const result = validatePageId(12345);

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error).toContain('string');
      }
    });

    it('should return failure for null', () => {
      const result = validatePageId(null);

      expect(result.ok).toBe(false);
    });

    it('should return failure for undefined', () => {
      const result = validatePageId(undefined);

      expect(result.ok).toBe(false);
    });
  });
});

describe('validateDriveId', () => {
  describe('given valid drive ID', () => {
    it('should return success with the validated CUID2', () => {
      const result = validateDriveId(VALID_CUID2_2);

      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.value).toBe(VALID_CUID2_2);
      }
    });
  });

  describe('given invalid drive ID', () => {
    it('should return failure for SQL injection attempt', () => {
      const result = validateDriveId("' OR '1'='1");

      expect(result.ok).toBe(false);
    });

    it('should return failure for extremely long string', () => {
      const result = validateDriveId('a'.repeat(1000));

      expect(result.ok).toBe(false);
    });
  });
});

describe('validateConversationId', () => {
  describe('given valid conversation ID', () => {
    it('should return success with the validated CUID2', () => {
      const result = validateConversationId(VALID_CUID2_3);

      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.value).toBe(VALID_CUID2_3);
      }
    });
  });

  describe('given invalid conversation ID', () => {
    it('should return failure for object payload', () => {
      const result = validateConversationId({ conversationId: VALID_CUID2_3 });

      expect(result.ok).toBe(false);
    });

    it('should return failure for array payload', () => {
      const result = validateConversationId([VALID_CUID2_3]);

      expect(result.ok).toBe(false);
    });
  });
});

describe('emitValidationError', () => {
  it('should emit error event with validation details', () => {
    const mockSocket = {
      emit: vi.fn(),
    };

    emitValidationError(mockSocket, 'join_channel', 'invalid Page ID format');

    expect(mockSocket.emit).toHaveBeenCalledWith('validation_error', {
      event: 'join_channel',
      error: 'invalid Page ID format',
    });
  });
});

/**
 * Integration tests for payload rejection scenarios
 * These tests verify that invalid payloads are rejected before any DB query
 */
describe('Integration: Invalid Payload Rejection', () => {
  describe('given malicious payloads', () => {
    it('should reject SQL injection in page ID', () => {
      const result = validatePageId("'; DROP TABLE pages; --");
      expect(result.ok).toBe(false);
    });

    it('should reject SQL injection in drive ID', () => {
      const result = validateDriveId("' OR '1'='1' --");
      expect(result.ok).toBe(false);
    });

    it('should reject SQL injection in conversation ID', () => {
      const result = validateConversationId("1; DELETE FROM dm_conversations;");
      expect(result.ok).toBe(false);
    });

    it('should reject path traversal attempts', () => {
      const result = validatePageId('../../../etc/passwd');
      expect(result.ok).toBe(false);
    });
  });

  describe('given DoS attempt payloads', () => {
    it('should reject extremely long page ID (10KB)', () => {
      const longPayload = 'a'.repeat(10240);
      const result = validatePageId(longPayload);
      expect(result.ok).toBe(false);
    });

    it('should reject extremely long drive ID (1MB)', () => {
      const longPayload = 'b'.repeat(1024 * 1024);
      const result = validateDriveId(longPayload);
      expect(result.ok).toBe(false);
    });

    it('should reject nested object payloads', () => {
      const nestedPayload = { id: { nested: { deep: { id: 'test' } } } };
      const result = validatePageId(nestedPayload);
      expect(result.ok).toBe(false);
    });

    it('should reject array payloads', () => {
      const arrayPayload = [VALID_CUID2_1, VALID_CUID2_2];
      const result = validateDriveId(arrayPayload);
      expect(result.ok).toBe(false);
    });
  });

  describe('given type coercion attack payloads', () => {
    it('should reject number that looks like valid data', () => {
      const result = validatePageId(12345678901234567890n);
      expect(result.ok).toBe(false);
    });

    it('should reject boolean true', () => {
      const result = validateDriveId(true);
      expect(result.ok).toBe(false);
    });

    it('should reject boolean false', () => {
      const result = validateConversationId(false);
      expect(result.ok).toBe(false);
    });

    it('should reject object with toString that returns valid CUID2', () => {
      const payload = {
        toString: () => VALID_CUID2_1,
      };
      const result = validatePageId(payload);
      expect(result.ok).toBe(false);
    });
  });

  describe('given edge case payloads', () => {
    it('should reject empty string', () => {
      const result = validatePageId('');
      expect(result.ok).toBe(false);
    });

    it('should reject whitespace-only string', () => {
      const result = validateDriveId('   ');
      expect(result.ok).toBe(false);
    });

    it('should reject CUID2 with leading whitespace', () => {
      const result = validateConversationId(' ' + VALID_CUID2_1);
      expect(result.ok).toBe(false);
    });

    it('should reject CUID2 with trailing whitespace', () => {
      const result = validatePageId(VALID_CUID2_1 + ' ');
      expect(result.ok).toBe(false);
    });

    it('should reject CUID2 with newline', () => {
      const result = validateDriveId(VALID_CUID2_1 + '\n');
      expect(result.ok).toBe(false);
    });

    it('should reject null byte injection', () => {
      const result = validateConversationId(VALID_CUID2_1 + '\x00malicious');
      expect(result.ok).toBe(false);
    });
  });

  describe('given valid CUID2 payloads (should pass)', () => {
    it('should accept valid page ID', () => {
      const result = validatePageId(VALID_CUID2_1);
      expect(result.ok).toBe(true);
    });

    it('should accept valid drive ID', () => {
      const result = validateDriveId(VALID_CUID2_2);
      expect(result.ok).toBe(true);
    });

    it('should accept valid conversation ID', () => {
      const result = validateConversationId(VALID_CUID2_3);
      expect(result.ok).toBe(true);
    });
  });
});
