import { describe, it, expect } from 'vitest';
import { NextRequest } from 'next/server';
import { GET } from '../route';

/**
 * Security Test Suite for Avatar Route - Path Traversal Prevention
 *
 * Tests cover path traversal vulnerabilities (OWASP A01: Broken Access Control)
 * ensuring malicious paths cannot escape the avatars directory.
 *
 * Note: Core path validation logic is thoroughly tested in safe-path.test.ts (33 tests).
 * These tests verify the route returns proper HTTP responses for malicious inputs.
 *
 * Tests for valid requests (serving actual files) require integration tests
 * with a real filesystem setup.
 */

// CUID2 format ID as used throughout the codebase (generated by @paralleldrive/cuid2)
const VALID_CUID2 = 'clh3am7ho0000ml08f8gth9r0';

describe('Avatar Route - Security Tests', () => {
  function createMockRequest(path: string): NextRequest {
    return new NextRequest(`http://localhost:3000${path}`);
  }

  function createParams(userId: string, filename: string): { params: Promise<{ userId: string; filename: string }> } {
    return {
      params: Promise.resolve({ userId, filename }),
    };
  }

  describe('Path Traversal Prevention', () => {
    it('should reject ../../../etc/passwd as filename', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/../../../etc/passwd`);
      const context = createParams(VALID_CUID2, '../../../etc/passwd');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject ../../.env as filename', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/../../.env`);
      const context = createParams(VALID_CUID2, '../../.env');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject URL-encoded traversal (decoded by Next.js)', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/..%2F..%2F.env`);
      const context = createParams(VALID_CUID2, '../../.env');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject backslash traversal (Windows-style)', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/..\\..\\secret.txt`);
      const context = createParams(VALID_CUID2, '..\\..\\secret.txt');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject very long filenames (DoS prevention)', async () => {
      const longFilename = 'a'.repeat(300) + '.png';
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/${longFilename}`);
      const context = createParams(VALID_CUID2, longFilename);

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject path traversal in userId', async () => {
      const request = createMockRequest('/api/avatar/../../../etc/passwd');
      const context = createParams('../../../etc', 'passwd');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject userId combined with filename traversal', async () => {
      const request = createMockRequest('/api/avatar/../../../.env');
      const context = createParams('..', '../.env');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject double-dot sequences in filename', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/file..png`);
      const context = createParams(VALID_CUID2, 'file..png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });
  });

  describe('User ID Validation', () => {
    it('should reject userId with invalid characters', async () => {
      const request = createMockRequest('/api/avatar/user@invalid.com/avatar.png');
      const context = createParams('user@invalid.com', 'avatar.png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject userId that is too short', async () => {
      const request = createMockRequest('/api/avatar/ab/avatar.png');
      const context = createParams('ab', 'avatar.png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject empty userId', async () => {
      const request = createMockRequest('/api/avatar//avatar.png');
      const context = createParams('', 'avatar.png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });
  });

  describe('Filename Validation', () => {
    it('should reject empty filename', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/`);
      const context = createParams(VALID_CUID2, '');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject filename with forward slashes', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/path/to/file.png`);
      const context = createParams(VALID_CUID2, 'path/to/file.png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject hidden files (starting with dot)', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/.hidden.png`);
      const context = createParams(VALID_CUID2, '.hidden.png');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });
  });

  describe('Extension Validation', () => {
    it('should reject non-image extensions', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/script.js`);
      const context = createParams(VALID_CUID2, 'script.js');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject .env files', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/config.env`);
      const context = createParams(VALID_CUID2, 'config.env');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });

    it('should reject executable files', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/malware.exe`);
      const context = createParams(VALID_CUID2, 'malware.exe');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
    });
  });

  describe('Response Security', () => {
    it('should not leak file paths in error responses', async () => {
      const request = createMockRequest(`/api/avatar/${VALID_CUID2}/../../../etc/passwd`);
      const context = createParams(VALID_CUID2, '../../../etc/passwd');

      const response = await GET(request, context);
      const body = await response.text();

      expect(body).not.toContain('/etc');
      expect(body).not.toContain('passwd');
      expect(body).not.toContain('storage');
    });

    it('should return 400 for validation errors without details', async () => {
      const request = createMockRequest(`/api/avatar/invalid/../../.env`);
      const context = createParams('invalid', '../../.env');

      const response = await GET(request, context);

      expect(response.status).toBe(400);
      const body = await response.text();
      expect(body).toBe('Bad Request');
    });
  });
});
