import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['src/**/*.{test,spec}.{ts,tsx,js,jsx}'],
    exclude: [
      // Integration tests that require a running PostgreSQL database
      'src/__tests__/cross-tenant-escalation.test.ts',
      'src/__tests__/device-auth-utils.test.ts',
      'src/__tests__/notifications.test.ts',
      'src/__tests__/permissions.test.ts',
      'src/__tests__/sheet-new-functions.test.ts',
      'src/auth/magic-link-service.test.ts',
      'src/auth/passkey-service.test.ts',
      'src/auth/__tests__/session-service.test.ts',
      'src/permissions/__tests__/permission-mutations.test.ts',
      'src/permissions/__tests__/zero-trust-boundaries.test.ts',
      'src/sheets/__tests__/sheet-store.integration.test.ts',
      'src/services/__tests__/app-shell-service.integration.test.ts',
      'src/services/__tests__/page-payload-service.integration.test.ts',
      'src/services/__tests__/org-membership-sync.integration.test.ts',
      'src/services/__tests__/drive-join-request-service.integration.test.ts',
      'src/services/__tests__/org-drive-visibility-lead.integration.test.ts',
      'src/permissions/__tests__/org-drive-resolvers.integration.test.ts',
      'src/permissions/__tests__/org-drive-sibling-resolvers.integration.test.ts',
      'src/permissions/__tests__/drive-gate-primitives.integration.test.ts',
      'src/permissions/__tests__/org-admin-access-audit.integration.test.ts',
      'src/agent-accounts/__tests__/account-facts-repository.integration.test.ts',
      'src/services/broadcast/__tests__/claim-recipient.integration.test.ts',
      'src/services/agent-workspaces/__tests__/agent-sessions-store.integration.test.ts',
      'src/services/app-hosting/__tests__/provisioner-claim.integration.test.ts',
      'src/tags/__tests__/tag-service.integration.test.ts',
      'src/auth/apple/__tests__/apple-token-store.integration.test.ts',
      'src/agent-accounts/__tests__/replay-store-repository.integration.test.ts',
      'src/agent-accounts/__tests__/adversarial/replay-across-replicas.integration.test.ts',
      'src/agent-accounts/__tests__/grant-gate-executor.integration.test.ts',
      'src/agent-accounts/__tests__/audit-repository.integration.test.ts',
      'src/agent-accounts/store/__tests__/store-adapter-infisical.integration.test.ts',
      'src/organizations/__tests__/org-services.integration.test.ts',
      'src/organizations/__tests__/org-member-revocation.integration.test.ts',
      'src/agent-accounts/executor/__tests__/pinned-https-client.integration.test.ts',
      'src/agent-accounts/__tests__/agent-account-repository.integration.test.ts',
      'src/agent-accounts/__tests__/plane-client.integration.test.ts',
      'src/agent-accounts/__tests__/adversarial/http-executor-end-to-end.integration.test.ts',
    ],
    setupFiles: ['./src/test/setup.ts'],
    // Run test files sequentially to avoid database race conditions
    fileParallelism: false,
    // Use forks pool for process-level module isolation between test files.
    // This prevents vi.mock() in unit tests from contaminating integration
    // tests that use real database connections.
    pool: 'forks',
    poolOptions: {
      forks: {
        singleFork: true,
      },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'json-summary'],
      reportsDirectory: './coverage',
      reportOnFailure: true,
      exclude: [
        '**/*.d.ts',
        '**/*.config.*',
        '**/dist/**',
        '**/test/**',
        '**/drizzle/**',
        '**/node_modules/**',
        // Integration tests excluded from the unit run above also must be
        // excluded from coverage — they never execute here, so counting them
        // as "0% covered" pulls the aggregate down artificially.
        'src/__tests__/cross-tenant-escalation.test.ts',
        'src/__tests__/device-auth-utils.test.ts',
        'src/__tests__/notifications.test.ts',
        'src/__tests__/permissions.test.ts',
        'src/__tests__/sheet-new-functions.test.ts',
        'src/auth/magic-link-service.test.ts',
        'src/auth/passkey-service.test.ts',
        'src/auth/__tests__/session-service.test.ts',
        'src/permissions/__tests__/permission-mutations.test.ts',
        'src/permissions/__tests__/zero-trust-boundaries.test.ts',
        'src/sheets/__tests__/sheet-store.integration.test.ts',
        'src/services/__tests__/app-shell-service.integration.test.ts',
        'src/services/__tests__/page-payload-service.integration.test.ts',
        'src/services/__tests__/org-membership-sync.integration.test.ts',
        'src/services/__tests__/drive-join-request-service.integration.test.ts',
        'src/services/__tests__/org-drive-visibility-lead.integration.test.ts',
        'src/permissions/__tests__/org-drive-resolvers.integration.test.ts',
      'src/permissions/__tests__/org-drive-sibling-resolvers.integration.test.ts',
      'src/permissions/__tests__/drive-gate-primitives.integration.test.ts',
      'src/permissions/__tests__/org-admin-access-audit.integration.test.ts',
      'src/agent-accounts/__tests__/account-facts-repository.integration.test.ts',
        'src/services/broadcast/__tests__/claim-recipient.integration.test.ts',
        'src/services/agent-workspaces/__tests__/agent-sessions-store.integration.test.ts',
        'src/services/app-hosting/__tests__/provisioner-claim.integration.test.ts',
        'src/tags/__tests__/tag-service.integration.test.ts',
      'src/auth/apple/__tests__/apple-token-store.integration.test.ts',
      'src/agent-accounts/__tests__/replay-store-repository.integration.test.ts',
      'src/agent-accounts/__tests__/adversarial/replay-across-replicas.integration.test.ts',
      'src/agent-accounts/__tests__/grant-gate-executor.integration.test.ts',
      'src/agent-accounts/__tests__/audit-repository.integration.test.ts',
      'src/agent-accounts/store/__tests__/store-adapter-infisical.integration.test.ts',
      'src/organizations/__tests__/org-services.integration.test.ts',
      'src/organizations/__tests__/org-member-revocation.integration.test.ts',
      'src/agent-accounts/executor/__tests__/pinned-https-client.integration.test.ts',
      'src/agent-accounts/__tests__/agent-account-repository.integration.test.ts',
      'src/agent-accounts/__tests__/plane-client.integration.test.ts',
      'src/agent-accounts/__tests__/adversarial/http-executor-end-to-end.integration.test.ts',
      ],
      thresholds: {
        lines: 85,
        branches: 94,
        functions: 88,
        statements: 85,
        // Pure sheet modules that moved here from apps/web, where that package's
        // per-glob gate pinned them at 100%. Restated so the move does not
        // silently relax them to this package's default — the relocation was to
        // share one definition of what rule edits are allowed, and a shared
        // definition tested less than its old home is a downgrade wearing a
        // refactor's clothes.
        'src/sheets/conditional-ops.ts': { lines: 100, branches: 100, functions: 100, statements: 100 },
        'src/sheets/palette.ts': { lines: 100, branches: 100, functions: 100, statements: 100 },
        'src/sheets/regions.ts': { lines: 100, branches: 100, functions: 100, statements: 100 },
        'src/sheets/format-request.ts': { lines: 100, branches: 100, functions: 100, statements: 100 },
        'src/sheets/region-format.ts': { lines: 100, branches: 100, functions: 100, statements: 100 },
      },
    },
  },
});
