#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 008 - Document Version Rollback Enhancement

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DOCKER SERVICES (PostgreSQL, Redis)
# ============================================

echo ""
echo "Starting Docker services (PostgreSQL, Redis)..."
docker-compose up -d postgres redis

wait_for_service 5432 "PostgreSQL"
wait_for_service 6379 "Redis"

# ============================================
# RUN DATABASE MIGRATIONS
# ============================================

echo ""
echo "Running database migrations..."
docker-compose up migrate

# ============================================
# START WEB SERVICE (Next.js)
# ============================================

echo ""
echo "Starting web service (Next.js)..."
cd apps/web
npm run dev &
WEB_PID=$!

wait_for_service 3000 "Web (Next.js)"

# ============================================
# START PROCESSOR SERVICE (Optional)
# ============================================

echo ""
echo "Starting processor service (optional, for embedded file handling)..."
cd ../../apps/processor
npm run dev &
PROCESSOR_PID=$!

wait_for_service 3003 "Processor"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Redis:      localhost:6379"
echo "  Web:        http://localhost:3000"
echo "  Processor:  http://localhost:3003"
echo ""
echo "PIDs:"
echo "  Web:       $WEB_PID"
echo "  Processor: $PROCESSOR_PID"
echo ""
echo "To stop services:"
echo "  kill $WEB_PID $PROCESSOR_PID"
echo "  docker-compose down"
echo ""
