import {
  Activity,
  ArrowUpRight,
  Bot,
  Cable,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  Ellipsis,
  File,
  FileCode,
  FileImage,
  FileSpreadsheet,
  FileText,
  Files,
  Flag,
  Folder,
  Hash,
  LayoutGrid,
  ListTodo,
  Lock,
  Menu,
  MessageSquare,
  MessagesSquare,
  Monitor,
  Moon,
  Plus,
  Puzzle,
  Search,
  Send,
  Settings,
  Share2,
  Sparkles,
  Sun,
  Square,
  SquareTerminal,
  Trash2,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react';

// DEC-8: lucide-react replaces myimago's hand-drawn set. The keys are the
// names myimago's shell uses, so ported call sites keep their icon names.
export const icons = {
  search: Search,
  chat: MessageSquare,
  files: Files,
  messages: MessagesSquare,
  tasks: ListTodo,
  calendar: Calendar,
  console: SquareTerminal,
  plugins: Puzzle,
  settings: Settings,
  folder: Folder,
  page: FileText,
  plus: Plus,
  sparkle: Sparkles,
  send: Send,
  share: Share2,
  grid: LayoutGrid,
  menu: Menu,
  close: X,
  arrowUpRight: ArrowUpRight,
  hash: Hash,
  check: Check,
  bot: Bot,
  flag: Flag,
  more: Ellipsis,
  trash: Trash2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  // The rail's ⋯ overflow (DEC-6).
  activity: Activity,
  connections: Cable,
  // A view-only thread's notice.
  lock: Lock,
  // The chat composer's Stop and a tool call's line.
  stop: Square,
  tool: Wrench,
  // Page types imago opens in classic (DEC-9), as classic draws them
  // (page-types.config iconName).
  canvas: FileImage,
  sheet: FileSpreadsheet,
  code: FileCode,
  file: File,
} as const satisfies Readonly<Record<string, LucideIcon>>;

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons) as readonly IconName[];
