import { pgTable, text, timestamp, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './auth';
import { sessions } from './sessions';

/**
 * Dev-preview GRANTS — the single-use handoff between the app origin and a
 * holder's dedicated preview origin.
 *
 * The dashboard frames `<app>/api/…/preview/open`; that route (session
 * authenticated, drive gate passed) inserts one row here and 302s the browser
 * to `https://<kind>-<holderId>.preview.<apex>/__pagespace/auth?grant=<id>`.
 * The preview host CONSUMES the row — one atomic conditional update that
 * succeeds only while `consumedAt IS NULL AND expiresAt > now` — and installs
 * the host-only preview cookie. A grant is therefore redeemable EXACTLY ONCE,
 * across every web replica, without a shared cache: the database is the
 * single-use ledger (ruling [A-preview-proxy], constraint 2).
 *
 * `id` is the capability: 256 random bits, generated by the store, never a
 * cuid (cuids are unique, not unguessable). Nothing else about the row is
 * secret. The row names the HOLDER polymorphically (`holderKind` +
 * `holderId`, CHECK-constrained to the two kinds) rather than by FK, because
 * a grant outliving its holder is harmless — it names a preview that no
 * longer exists and the gate refuses it — and a cascade would add a write
 * path to every holder teardown for no safety gain. `userId` DOES cascade:
 * a deleted user leaves no grant behind.
 *
 * `cookieExpiresAt` is fixed at mint time so the cookie's lifetime is decided
 * by the same authority that decided the grant's, and the auth endpoint
 * cannot be talked into a longer one. Rows are ephemeral (a one-minute
 * redemption window); the store sweeps expired rows opportunistically on
 * mint, bounded, so the table never needs a cron.
 */
export const devPreviewGrants = pgTable(
  'dev_preview_grants',
  {
    /** The capability itself — 256 random bits, base64url. Set by the store, no default on purpose. */
    id: text('id').primaryKey(),
    holderKind: text('holderKind').notNull(),
    holderId: text('holderId').notNull(),
    userId: text('userId')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /**
     * The PageSpace session that minted this grant, carried into the cookie so
     * the per-request gather can reject a preview whose session has been
     * revoked. NOT NULL: grants are ephemeral (a 60-second redemption window,
     * swept opportunistically) and the feature is dark, so there is nothing to
     * backfill and no reason to admit a grant that cannot be revoked. Cascades
     * like `userId` — a deleted session takes its outstanding grants with it.
     */
    sessionId: text('sessionId')
      .notNull()
      .references(() => sessions.id, { onDelete: 'cascade' }),
    /** Until when the grant may be redeemed. */
    expiresAt: timestamp('expiresAt', { mode: 'date' }).notNull(),
    /** Until when the cookie the redemption installs authenticates. */
    cookieExpiresAt: timestamp('cookieExpiresAt', { mode: 'date' }).notNull(),
    /** Stamped by the ONE successful redemption; a second redemption finds it set and fails. */
    consumedAt: timestamp('consumedAt', { mode: 'date' }),
    createdAt: timestamp('createdAt', { mode: 'date' }).notNull(),
  },
  (table) => ({
    expiresAtIdx: index('dev_preview_grants_expires_at_idx').on(table.expiresAt),
    holderKindCheck: check('dev_preview_grants_holder_kind_check', sql`${table.holderKind} IN ('workspace', 'env')`),
  }),
);

export type DevPreviewGrant = typeof devPreviewGrants.$inferSelect;
