/**
 * Socket.IO room grammar — the ONE definition of every room-name shape (#2158).
 *
 * Consumed by:
 * - the realtime join sites (apps/realtime/src/index.ts socket.join calls),
 * - the broadcast audience validator (apps/realtime/src/broadcast-audience.ts),
 * - the kick room sets (apps/realtime/src/kick-handler.ts and the
 *   permission-mutation revocation hook in ../permissions/revocation-kick.ts),
 * - the web broadcast emitters (apps/web/src/lib/websocket/).
 *
 * Because the builders and the validator live in one module, a new room shape
 * added here is automatically joinable, broadcastable, and kickable; a shape
 * invented anywhere else is rejected by `isKnownRoomId` and flagged by the
 * drift guard (apps/realtime/src/__tests__/room-grammar-drift-guard.test.ts).
 *
 * TRUST MODEL — room membership is a delivery optimization, NOT the
 * authorization boundary. The authoritative "who may receive/act on events for
 * this resource" fact lives in Postgres, enforced by:
 * - join-time permission checks (getUserAccessLevel / getUserDriveAccess /
 *   DM participant filter-in-query) before any socket.join, and
 * - per-event re-authorization for sensitive events
 *   (apps/realtime/src/per-event-auth.ts), which re-queries Postgres.
 * Revocation kicks (the /api/kick path) merely shrink the window in which a
 * revoked-but-still-connected socket keeps receiving room fan-out; they are
 * best-effort by design and nothing security-critical may depend on them.
 *
 * Everything in this module is pure: no I/O, no state.
 */

import { globalChannelId } from '../ai/global-channel-id';

// CUID2 format: starts with a lowercase letter, then lowercase alphanumerics
// (min 2, max 32 chars) — generated by @paralleldrive/cuid2, PageSpace's ID
// format. Length-checked before the regex to prevent ReDoS.
const CUID2_REGEX = /^[a-z][a-z0-9]{1,31}$/;
const MAX_CUID2_LENGTH = 32;

/** Type guard: is `input` a CUID2-shaped string? Pure predicate. */
export const isCUID2 = (input: unknown): input is string => {
  if (typeof input !== 'string') return false;
  if (input.length > MAX_CUID2_LENGTH) return false;
  if (input.length < 2) return false;
  return CUID2_REGEX.test(input);
};

// ---------------------------------------------------------------------------
// Builders — one per joinable room shape
// ---------------------------------------------------------------------------

/** Page / channel room: the bare pageId. */
export const pageRoom = (pageId: string): string => pageId;

/** Per-user notifications room. */
export const notificationsRoom = (userId: string): string => `notifications:${userId}`;

/** Per-user task feed room. */
export const userTasksRoom = (userId: string): string => `user:${userId}:tasks`;

/** Per-user calendar feed room. */
export const userCalendarRoom = (userId: string): string => `user:${userId}:calendar`;

/** Per-user drive list room. */
export const userDrivesRoom = (userId: string): string => `user:${userId}:drives`;

/**
 * Per-user global assistant room. Delegates to the global-channel id the AI
 * pipeline already uses — the room IS that channel id (`user:<id>:global`).
 */
export const userGlobalRoom = (userId: string): string => globalChannelId(userId);

/** Drive room. */
export const driveRoom = (driveId: string): string => `drive:${driveId}`;

/** Drive calendar room. */
export const driveCalendarRoom = (driveId: string): string => `drive:${driveId}:calendar`;

/** Direct-message conversation room. */
export const dmRoom = (conversationId: string): string => `dm:${conversationId}`;

/** Drive activity feed room. */
export const driveActivityRoom = (driveId: string): string => `activity:drive:${driveId}`;

/** Page activity feed room. */
export const pageActivityRoom = (pageId: string): string => `activity:page:${pageId}`;

/**
 * Every builder, for grammar-wide assertions (drift guard: each output must be
 * accepted by `isKnownRoomId` and by the broadcast audience validator).
 */
export const ALL_ROOM_BUILDERS: ReadonlyArray<(id: string) => string> = [
  pageRoom,
  notificationsRoom,
  userTasksRoom,
  userCalendarRoom,
  userDrivesRoom,
  userGlobalRoom,
  driveRoom,
  driveCalendarRoom,
  dmRoom,
  driveActivityRoom,
  pageActivityRoom,
];

// ---------------------------------------------------------------------------
// Validator — accepts exactly the shapes the builders produce
// ---------------------------------------------------------------------------

/** Suffix-keyed `user:<cuid>:<suffix>` rooms. */
const USER_SUFFIXES = new Set(['tasks', 'calendar', 'drives', 'global']);

/** `activity:<scope>:<cuid>` scopes. */
const ACTIVITY_SCOPES = new Set(['drive', 'page']);

/**
 * Returns true iff `roomId` matches one of the room shapes the builders above
 * produce (with a CUID2 in the identifier position). Pure; no side effects.
 */
export function isKnownRoomId(roomId: string): boolean {
  const segments = roomId.split(':');

  // Bare pageId / channelId room: a CUID2 with no prefix.
  if (segments.length === 1) {
    return isCUID2(roomId);
  }

  // notifications:<cuid> | dm:<cuid> | drive:<cuid>
  if (segments.length === 2 && (segments[0] === 'notifications' || segments[0] === 'dm' || segments[0] === 'drive')) {
    return isCUID2(segments[1]);
  }

  // drive:<cuid>:calendar
  if (segments.length === 3 && segments[0] === 'drive' && segments[2] === 'calendar') {
    return isCUID2(segments[1]);
  }

  // user:<cuid>:<suffix>
  if (segments.length === 3 && segments[0] === 'user' && USER_SUFFIXES.has(segments[2])) {
    return isCUID2(segments[1]);
  }

  // activity:<scope>:<cuid>
  if (segments.length === 3 && segments[0] === 'activity' && ACTIVITY_SCOPES.has(segments[1])) {
    return isCUID2(segments[2]);
  }

  return false;
}

// ---------------------------------------------------------------------------
// Kick room sets — the rooms a revocation must evict a user from
// ---------------------------------------------------------------------------

/** Every drive-scoped room a user must leave when their drive access is revoked. */
export const roomsForDriveKick = (driveId: string): string[] => [
  driveRoom(driveId),
  driveCalendarRoom(driveId),
  driveActivityRoom(driveId),
];

/** Every page-scoped room a user must leave when their page access is revoked. */
export const roomsForPageKick = (pageId: string): string[] => [
  pageRoom(pageId),
  pageActivityRoom(pageId),
];
