/**
 * Socket.IO room grammar — the ONE definition of every room-name shape (#2158).
 *
 * Consumed by:
 * - the realtime join sites (apps/realtime/src/index.ts socket.join calls),
 * - the broadcast audience validator (apps/realtime/src/broadcast-audience.ts),
 * - the kick room sets (apps/realtime/src/kick-handler.ts and the
 *   permission-mutation revocation hook in ../permissions/revocation-kick.ts),
 * - the web broadcast emitters (apps/web/src/lib/websocket/).
 *
 * Because the builders and the validator live in one module, a new room shape
 * added here is automatically joinable, broadcastable, and kickable; a shape
 * invented anywhere else is rejected by `isKnownRoomId` and flagged by the
 * drift guard (apps/realtime/src/__tests__/room-grammar-drift-guard.test.ts).
 *
 * TRUST MODEL — room membership is a delivery optimization, NOT the
 * authorization boundary. The authoritative "who may receive/act on events for
 * this resource" fact lives in Postgres, enforced by:
 * - join-time permission checks (getUserAccessLevel / getUserDriveAccess /
 *   DM participant filter-in-query) before any socket.join, and
 * - per-event re-authorization for sensitive events
 *   (apps/realtime/src/per-event-auth.ts), which re-queries Postgres.
 * Revocation kicks (the /api/kick path) merely shrink the window in which a
 * revoked-but-still-connected socket keeps receiving room fan-out; they are
 * best-effort by design and nothing security-critical may depend on them.
 *
 * Everything in this module is pure: no I/O, no state.
 */

import { globalChannelId } from '../ai/global-channel-id';

// CUID2 format: starts with a lowercase letter, then lowercase alphanumerics
// (min 2, max 32 chars) — generated by @paralleldrive/cuid2, PageSpace's ID
// format. Length-checked before the regex to prevent ReDoS.
//
// Deliberately NOT the official `isCuid` from @paralleldrive/cuid2 (also
// wrapped by ../validators/id-validators.ts's `isValidId`): that validator's
// regex is `/^[0-9a-z]+$/`, which accepts a LEADING DIGIT — looser than what
// PageSpace's own `createId()` ever actually produces (it always prepends a
// random letter). This is a broadcast-audience-adjacent security boundary
// (rejecting malformed/attacker-controlled channelIds), so it intentionally
// matches the generator's real invariant rather than the more permissive
// general-purpose spec check used for ordinary ID parsing elsewhere.
const CUID2_REGEX = /^[a-z][a-z0-9]{1,31}$/;
const MAX_CUID2_LENGTH = 32;

/** Type guard: is `input` a CUID2-shaped string? Pure predicate. */
export const isCUID2 = (input: unknown): input is string => {
  if (typeof input !== 'string') return false;
  if (input.length > MAX_CUID2_LENGTH) return false;
  if (input.length < 2) return false;
  return CUID2_REGEX.test(input);
};

// ---------------------------------------------------------------------------
// Builders — one per joinable room shape
// ---------------------------------------------------------------------------

/** Page / channel room: the bare pageId. */
export const pageRoom = (pageId: string): string => pageId;

/** Per-user notifications room. */
export const notificationsRoom = (userId: string): string => `notifications:${userId}`;

/** Per-user task feed room. */
export const userTasksRoom = (userId: string): string => `user:${userId}:tasks`;

/** Per-user calendar feed room. */
export const userCalendarRoom = (userId: string): string => `user:${userId}:calendar`;

/** Per-user drive list room. */
export const userDrivesRoom = (userId: string): string => `user:${userId}:drives`;

/**
 * Per-user global assistant room. Delegates to the global-channel id the AI
 * pipeline already uses — the room IS that channel id (`user:<id>:global`).
 */
export const userGlobalRoom = (userId: string): string => globalChannelId(userId);

/** Drive room. */
export const driveRoom = (driveId: string): string => `drive:${driveId}`;

/** Drive calendar room. */
export const driveCalendarRoom = (driveId: string): string => `drive:${driveId}:calendar`;

/** Direct-message conversation room. */
export const dmRoom = (conversationId: string): string => `dm:${conversationId}`;

/**
 * Agent-session workspace room (`session:<agent_workspaces.id>`) — the layout
 * plane for one workspace: `workspace:updated` (rev-carrying pane-grid
 * events) fan out here (epic Phase 3). Clients join from
 * `useWorkspaceLayoutSync`, which holds this room for the ONE workspace whose
 * grid is on screen — distinct from `user:<id>:sessions`, the directory plane
 * carrying every workspace a user owns. Two rooms because the audiences
 * genuinely differ, not because the concept does.
 */
export const sessionRoom = (workspaceId: string): string => `session:${workspaceId}`;

/**
 * AI conversation content room (`conv:<conversationId>`) — the content plane
 * of the Agent-Session Single Source of Truth epic (Phase 2). Joined on pane
 * open via the `join_conversation` handler, which authorizes with
 * `canAccessConversation` (owner OR isShared + page access). Carries the
 * authoritative `conversation:message_*` / `conversation:undo_applied` events
 * plus the transitional `chat:stream_start/complete` mirror.
 */
export const conversationRoom = (conversationId: string): string => `conv:${conversationId}`;

/**
 * Per-user session/conversation directory room (`user:<id>:sessions`) —
 * the directory plane. Auto-joined on connect alongside the other personal
 * rooms; carries id-level `conversation:created/updated/closed/reopened/
 * deleted` events so sidebars and session lists can update without joining
 * every conversation's own room.
 */
export const userSessionsRoom = (userId: string): string => `user:${userId}:sessions`;

/** Drive activity feed room. */
export const driveActivityRoom = (driveId: string): string => `activity:drive:${driveId}`;

/** Page activity feed room. */
export const pageActivityRoom = (pageId: string): string => `activity:page:${pageId}`;

/**
 * Every builder, for grammar-wide assertions (drift guard: each output must be
 * accepted by `isKnownRoomId` and by the broadcast audience validator).
 */
export const ALL_ROOM_BUILDERS: ReadonlyArray<(id: string) => string> = [
  pageRoom,
  notificationsRoom,
  userTasksRoom,
  userCalendarRoom,
  userDrivesRoom,
  userGlobalRoom,
  userSessionsRoom,
  driveRoom,
  driveCalendarRoom,
  dmRoom,
  sessionRoom,
  conversationRoom,
  driveActivityRoom,
  pageActivityRoom,
];

// ---------------------------------------------------------------------------
// Validator — accepts exactly the shapes the builders produce
// ---------------------------------------------------------------------------

/** Suffix-keyed `user:<cuid>:<suffix>` rooms. */
const USER_SUFFIXES = new Set(['tasks', 'calendar', 'drives', 'global', 'sessions']);

/** `activity:<scope>:<cuid>` scopes. */
const ACTIVITY_SCOPES = new Set(['drive', 'page']);

/**
 * Returns true iff `roomId` matches one of the room shapes the builders above
 * produce (with a CUID2 in the identifier position). Pure; no side effects.
 */
export function isKnownRoomId(roomId: string): boolean {
  const segments = roomId.split(':');

  // Bare pageId / channelId room: a CUID2 with no prefix.
  if (segments.length === 1) {
    return isCUID2(roomId);
  }

  // notifications:<cuid> | dm:<cuid> | drive:<cuid> | session:<cuid> | conv:<cuid>
  if (
    segments.length === 2 &&
    (segments[0] === 'notifications' ||
      segments[0] === 'dm' ||
      segments[0] === 'drive' ||
      segments[0] === 'session' ||
      segments[0] === 'conv')
  ) {
    return isCUID2(segments[1]);
  }

  // drive:<cuid>:calendar
  if (segments.length === 3 && segments[0] === 'drive' && segments[2] === 'calendar') {
    return isCUID2(segments[1]);
  }

  // user:<cuid>:<suffix>
  if (segments.length === 3 && segments[0] === 'user' && USER_SUFFIXES.has(segments[2])) {
    return isCUID2(segments[1]);
  }

  // activity:<scope>:<cuid>
  if (segments.length === 3 && segments[0] === 'activity' && ACTIVITY_SCOPES.has(segments[1])) {
    return isCUID2(segments[2]);
  }

  return false;
}

// ---------------------------------------------------------------------------
// Kick room sets — the rooms a revocation must evict a user from
// ---------------------------------------------------------------------------

/**
 * The kick sets come in two shapes, and the difference is load-bearing
 * (security review HIGH 3).
 *
 * A DRIVE or PAGE revocation names one id, and the drive/page/activity rooms
 * are all DERIVABLE from it — one pure function, no IO. The rooms the
 * agent-session epic added are not: `conv:<conversationId>` and
 * `session:<workspaceId>` are keyed by ids the revocation does not know, so
 * they can only be reached by ENUMERATING what the revoked grant covered.
 * That is why they are separate builders, fed by the enumeration in
 * ../permissions/revocation-kick.ts, rather than extra entries below.
 *
 * The trap that produced the finding: because the two static sets were the
 * ONLY sets, adding a room shape that these functions could not express meant
 * silently adding a room no revocation kicked. `rooms.test.ts` now asserts
 * that every shape in {@link ALL_ROOM_BUILDERS} is either covered by some
 * kick set or explicitly personal, so a future shape cannot slip through the
 * same gap.
 */

/** Every drive-scoped room a user must leave when their drive access is revoked. */
export const roomsForDriveKick = (driveId: string): string[] => [
  driveRoom(driveId),
  driveCalendarRoom(driveId),
  driveActivityRoom(driveId),
];

/** Every page-scoped room a user must leave when their page access is revoked. */
export const roomsForPageKick = (pageId: string): string[] => [
  pageRoom(pageId),
  pageActivityRoom(pageId),
];

/**
 * The content room of ONE conversation a revocation reached. Enumerated, not
 * derived: a page revocation must find the conversations that page carried,
 * because `conv:<id>` is keyed by conversation and the page id cannot produce
 * it. Pre-epic this room did not exist and page-chat content rode the page
 * room, which {@link roomsForPageKick} already covers — moving the content
 * plane here without extending revocation is exactly what left a revoked
 * member receiving full `conversation:message_created` payloads.
 */
export const roomsForConversationKick = (conversationId: string): string[] => [
  conversationRoom(conversationId),
];

/**
 * The layout room of ONE agent workspace a revocation reached. Enumerated for
 * the same reason: `session:<workspaceId>` carries `workspace:updated` grids
 * for a workspace in the drive whose membership was just revoked, and the
 * drive id alone cannot name it.
 */
export const roomsForWorkspaceKick = (workspaceId: string): string[] => [sessionRoom(workspaceId)];
