/**
 * Machine Projects: add / list / remove git repos on a Machine's persistent
 * filesystem (IO, dependency-injected where it touches the sandbox/DB).
 *
 * A Machine's identity is its backing page (`machineId`) — the SAME page
 * whose persistent Sprite session (`machine_sessions`, see
 * services/sandbox/machine-session-manager.ts) a live Terminal shell, or a
 * page-agent's "own machine" tool calls (services/sandbox/machine-session.ts),
 * already reconnects to. `addProject` acquires and execs against that exact
 * session (via the injected `acquireMachineSandbox`/`reconnect`, which
 * production wiring binds through the MachineHost seam — see
 * sandbox-client/sprite-machine-host.ts / machine-host-adapter.ts) so a
 * cloned repo shows up in the same filesystem the human/agent already sees.
 *
 * `addProject` clones through `runGitInSandbox` — the SAME hardened git
 * execution path the agent's `git_clone` tool uses (packages/lib/src/
 * services/sandbox/git-tool-runners.ts): the acting user's GitHub token is
 * fetched per-call and injected into the child process's env only for that
 * one command, via a one-shot credential helper — never written to argv,
 * never persisted to the machine's disk or git config. `runGitInSandbox`
 * itself is unmodified; only its `acquireSandbox`/`reconnect` deps are bound
 * here to the target machine.
 *
 * `SandboxActorContext.conversationId` is a required field designed around
 * conversation-scoped sandboxes; a Machine op has no conversation, so it is
 * repurposed here as an opaque scope key (the machineId) that the injected
 * `acquireSandbox` closure ignores in favor of the actual bound machine —
 * documented at the call site below.
 */

import type { SubscriptionTier } from '../subscription-utils';
import { runGitInSandbox, type GitSandboxRunDeps } from '../sandbox/git-tool-runners';
import type { SandboxActorContext, SandboxQuotaDeps } from '../sandbox/tool-runners';
import { SANDBOX_TIMEOUT_MS, SANDBOX_MAX_OUTPUT_BYTES } from '../sandbox/execution-policy';
import type { ExecutableSandbox } from '../sandbox/sandbox-client/types';
import type { CodeExecutionAuditInput } from '../sandbox/audit';
import { isValidId } from '../../validators/id-validators';
import { resolveProjectClonePath, isValidRepoUrl, normalizeProjectName } from './project-paths';
import { isUniqueViolation, type MachineProjectStore, type MachineProjectRecord } from './machine-projects-store';

export type AddProjectDenialReason = 'invalid_name' | 'invalid_repo_url' | 'duplicate_name';

/**
 * Pure decision: is this (name, repoUrl) addable to a machine with these
 * existing project names? The name is free text — it is NORMALIZED into a
 * directory-safe slug rather than rejected (`normalizeProjectName`), and the
 * normalized form is what the duplicate check and the persisted row use. The
 * repo URL still rejects, since there is no meaningful way to normalize a
 * non-HTTPS remote into an HTTPS one.
 *
 * `projectId` is the row id this operation will persist, generated by the
 * caller BEFORE anything touches the filesystem: the clone path is derived
 * from it (`resolveProjectClonePath`), so the directory is unique per ROW,
 * not per name. That per-row uniqueness is the fix for the old by-name
 * TOCTOU: two concurrent adds of the same name used to clone into ONE
 * directory, the loser's clone failed ("destination exists"), and its cleanup
 * `rm -rf`ed the WINNER's fresh checkout. Now they cannot share a path at all.
 */
export function planAddProject({
  name,
  repoUrl,
  existingNames,
  projectId,
}: {
  name: string;
  repoUrl: string;
  existingNames: string[];
  projectId: string;
}): { ok: true; name: string; path: string } | { ok: false; reason: AddProjectDenialReason } {
  if (!isValidRepoUrl(repoUrl)) return { ok: false, reason: 'invalid_repo_url' };

  // A malformed row id is a WIRING fault (`newProjectId` misbound to a
  // non-cuid2 generator), not user input — throw loudly rather than mislabel
  // every add on the instance as the USER's `invalid_name` (a 400 blaming a
  // name that is actually fine).
  if (!isValidId(projectId)) {
    throw new Error(
      `planAddProject: projectId ${JSON.stringify(projectId)} is not a valid cuid2 row id — check the newProjectId dep`,
    );
  }

  const normalized = normalizeProjectName(name);
  const path = resolveProjectClonePath(normalized, projectId);
  // Unreachable given the normalizer's invariant (its output always satisfies
  // `isValidProjectName`) and the id gate above; kept as the second confinement
  // gate, so a regression in the normalizer or `resolvePathWithinSync` fails
  // closed HERE rather than escaping PROJECTS_ROOT.
  if (!path) return { ok: false, reason: 'invalid_name' };

  if (existingNames.includes(normalized)) return { ok: false, reason: 'duplicate_name' };
  return { ok: true, name: normalized, path };
}

export interface MachineActorContext {
  userId: string;
  tenantId: string;
  actorEmail: string;
  actorDisplayName?: string;
  tier: SubscriptionTier;
}

export type MachineAcquireResult =
  | { ok: true; sandboxId: string; resumed: boolean }
  | { ok: false; reason: string; cause?: unknown };

export interface MachineProjectsDeps {
  store: MachineProjectStore;
  isEnabled: () => boolean;
  now: () => Date;
  /**
   * Generate the id for a project row BEFORE its clone runs — production
   * wiring binds cuid2's `createId` (the same generator as the schema
   * default, which this deliberately bypasses so the clone path and the row
   * can share one id). Injected so tests are deterministic.
   */
  newProjectId: () => string;
  /** Acquire a live, authorized sandbox for this machine's backing page — pre-bound to tenant/owner/canRun by the caller. */
  acquireMachineSandbox: (machineId: string) => Promise<MachineAcquireResult>;
  reconnect: (sandboxId: string) => Promise<ExecutableSandbox | null>;
  resolveGitHubToken: (userId: string) => Promise<string | null>;
  quota: SandboxQuotaDeps;
  buildEnv: () => Record<string, string>;
  audit: (input: CodeExecutionAuditInput) => Promise<void>;
  screenOutput?: (text: string) => Promise<string>;
  /**
   * Identity-guarded kill of a PROMOTED project's own Sprite (`MachineHost.kill`
   * shape) — used by `removeProject` so deleting a promoted project stops its
   * billing microVM immediately rather than leaving it to the reclaim outbox
   * cron. Optional: absent (older wiring) means the DELETE trigger's outbox
   * pointer is the only reclaim path, which is safe but slower.
   */
  killSprite?: (input: {
    sandboxId: string;
    spriteInstanceId: string | null;
  }) => Promise<{ ok: boolean }>;
}

function buildGitRunDeps(machineId: string, deps: MachineProjectsDeps): GitSandboxRunDeps {
  return {
    isEnabled: deps.isEnabled,
    resolveGitHubToken: deps.resolveGitHubToken,
    acquireSandbox: async () => {
      const result = await deps.acquireMachineSandbox(machineId);
      if (!result.ok) return { ok: false, reason: 'provision_failed' };
      return { ok: true, sandboxId: result.sandboxId, resumed: result.resumed };
    },
    reconnect: deps.reconnect,
    quota: deps.quota,
    buildEnv: deps.buildEnv,
    audit: deps.audit,
    screenOutput: deps.screenOutput,
    now: deps.now,
  };
}

function buildCtx(machineId: string, actor: MachineActorContext): SandboxActorContext {
  return {
    userId: actor.userId,
    tenantId: actor.tenantId,
    driveId: undefined,
    // See module doc: a Machine op has no conversation, so this opaque scope
    // key (ignored by the acquireSandbox closure above) just satisfies the field.
    conversationId: machineId,
    actorEmail: actor.actorEmail,
    actorDisplayName: actor.actorDisplayName,
    tier: actor.tier,
  };
}

// Best-effort: remove a directory from the machine's filesystem. Never
// throws — used both to clean up a failed/partial clone and to remove a
// project's checkout on `removeProject`.
async function safeRemoveDirectory(
  machineId: string,
  path: string,
  deps: MachineProjectsDeps,
): Promise<void> {
  try {
    const acquired = await deps.acquireMachineSandbox(machineId);
    if (!acquired.ok) return;
    const sandbox = await deps.reconnect(acquired.sandboxId);
    if (!sandbox) return;
    await sandbox.runCommand({
      cmd: 'rm',
      args: ['-rf', path],
      timeoutMs: SANDBOX_TIMEOUT_MS,
      maxBytes: SANDBOX_MAX_OUTPUT_BYTES,
    });
  } catch {
    // best-effort
  }
}

export type AddProjectResult =
  | { ok: true; project: MachineProjectRecord }
  | { ok: false; reason: AddProjectDenialReason | 'kill_switch_off' | 'clone_failed' | 'error'; detail?: string };

export async function addProject({
  machineId,
  actor,
  name,
  repoUrl,
  deps,
}: {
  machineId: string;
  actor: MachineActorContext;
  name: string;
  repoUrl: string;
  deps: MachineProjectsDeps;
}): Promise<AddProjectResult> {
  if (!deps.isEnabled()) return { ok: false, reason: 'kill_switch_off' };

  const existing = await deps.store.list(machineId);
  const projectId = deps.newProjectId();
  const plan = planAddProject({ name, repoUrl, existingNames: existing.map((p) => p.name), projectId });
  if (!plan.ok) return plan;

  const ctx = buildCtx(machineId, actor);
  const gitDeps = buildGitRunDeps(machineId, deps);

  const result = await runGitInSandbox({
    cmd: 'git',
    args: ['clone', repoUrl, plan.path],
    ctx,
    deps: gitDeps,
  });

  if (!result.success) {
    // A clone that never returned an exit code (timeout, transport error) can
    // still have left a partial checkout. Under per-row paths that orphan is
    // PERMANENT if not removed here — no row will ever point at it and no
    // retry reuses this id — unlike the old shared by-name directory, which
    // the next same-name attempt reclaimed. Same id-scoped cleanup as below:
    // this directory is ours alone.
    await safeRemoveDirectory(machineId, plan.path, deps);
    return { ok: false, reason: 'clone_failed', detail: result.error };
  }
  if (result.exitCode !== 0) {
    // Cleanup of OUR OWN partial clone only. The path is derived from the row
    // id this operation just generated (`resolveProjectClonePath`), so no
    // concurrent add — even of the SAME name — can be inside it: the old
    // by-name TOCTOU (loser's cleanup `rm -rf`ing the winner's checkout out of
    // the shared by-name directory) is structurally impossible here.
    await safeRemoveDirectory(machineId, plan.path, deps);
    return { ok: false, reason: 'clone_failed', detail: result.stderr || result.stdout };
  }

  try {
    const project = await deps.store.create({
      id: projectId,
      ownerId: actor.userId,
      machineId,
      // The normalized name — never the raw text the caller typed. Persisting
      // anything else would desync the row from the directory just cloned.
      name: plan.name,
      repoUrl,
      path: plan.path,
      now: deps.now(),
    });
    return { ok: true, project };
  } catch (error) {
    if (isUniqueViolation(error)) {
      // Lost a same-name race at the INSERT (the name stays unique per machine
      // even though paths no longer are): our clone SUCCEEDED into our own
      // per-row directory, but no row will ever point at it — remove it, or it
      // lingers as an unreachable orphan. Still id-scoped: this is our
      // directory, never the winner's. The loser paying for a full clone
      // before losing is the accepted price of never sharing a directory —
      // reserving the name before the clone was tried and reverted (see the
      // planAddProject doc).
      await safeRemoveDirectory(machineId, plan.path, deps);
      return { ok: false, reason: 'duplicate_name' };
    }
    // Deliberately NO directory cleanup here: unlike the unique violation
    // above (the insert definitively did not happen), a generic store error is
    // AMBIGUOUS — the insert may have committed with only the ack lost, and
    // `rm -rf` would then delete a LIVE row's checkout, the exact data loss
    // this module exists to prevent. A leaked directory is the safer failure.
    return { ok: false, reason: 'error', detail: error instanceof Error ? error.message : String(error) };
  }
}

export async function listProjects({
  machineId,
  store,
}: {
  machineId: string;
  store: MachineProjectStore;
}): Promise<MachineProjectRecord[]> {
  return store.list(machineId);
}

export type RemoveProjectResult = { ok: true } | { ok: false; reason: 'not_found' | 'error' };

/**
 * Remove a project. Normalizes its lookup key for the same reason
 * `attachBranch`/`killBranch` do: `addProject` persists the CANONICAL name, so
 * whatever free text created a project must also be able to delete it. A name
 * read back from `listProjects` is already canonical and passes through
 * unchanged, because normalization is idempotent.
 */
export async function removeProject({
  machineId,
  name: requestedName,
  deps,
}: {
  machineId: string;
  name: string;
  deps: MachineProjectsDeps;
}): Promise<RemoveProjectResult> {
  const name = normalizeProjectName(requestedName);
  const existing = await deps.store.findByName(machineId, name);
  if (!existing) return { ok: false, reason: 'not_found' };

  // A PROMOTED project's Sprite is a real billing microVM, findable only via
  // this row. Best-effort identity-guarded kill BEFORE the row goes away: on
  // failure the delete still proceeds — the AFTER DELETE trigger copies the
  // pointer into the reclaim outbox, and the orphan reconciler retries the
  // kill forever — but waiting for a cron is a worse default than stopping the
  // meter now. Skipped for a torn-down row: `sandboxId` is a NAME reused
  // across re-creates, and re-killing it could destroy a replacement VM.
  if (existing.sandboxId && !existing.spriteTornDownAt && deps.killSprite) {
    try {
      await deps.killSprite({
        sandboxId: existing.sandboxId,
        spriteInstanceId: existing.spriteInstanceId,
      });
    } catch {
      // Best-effort; the delete trigger's outbox pointer covers this Sprite.
    }
  }

  // Best-effort filesystem cleanup of THIS ROW's own directory (its persisted
  // `path` — never a path re-derived from the name, which for pre-per-row-path
  // rows wouldn't even match). The tracking row is removed regardless of
  // whether `rm -rf` succeeds, since the user asked for the project gone from
  // their list; a lingering directory is far less surprising than a project
  // the user can never remove because the machine is briefly unreachable.
  await safeRemoveDirectory(machineId, existing.path, deps);

  try {
    // By id, not by name: a by-name delete could race a concurrent
    // remove-then-re-add of this name and delete the NEW row (whose own
    // directory the `rm -rf` above never touched).
    await deps.store.remove(machineId, existing.id);
    return { ok: true };
  } catch {
    return { ok: false, reason: 'error' };
  }
}
