/**
 * Client-side PKCE (RFC 7636) math for the OAuth 2.1 authorization-code +
 * PKCE flow (`pagespace login`, `packages/cli/src/auth/loopback-flow.ts`).
 *
 * Pure: no clock, no ambient randomness — every decision is a function of
 * its arguments only. Uses the Web Crypto API (`crypto.subtle`, `btoa`)
 * rather than `node:crypto`/`Buffer` so this module runs unmodified in a
 * browser bundle — this file is reachable from the SDK's public entry point,
 * so a plain browser app implementing its own login flow needs it to work
 * without Node polyfills. Deliberately copied (not imported) from the
 * provider-side implementation (`packages/lib/src/auth/oauth/pkce.ts`, which
 * also verifies challenges server-side and pulls in `packages/lib`'s
 * `secureCompare`): the published SDK must never runtime-import
 * `@pagespace/lib` (see `operations/roles.ts`'s equivalent inlining of
 * `PagePerm`, for the same reason) — the derivation itself is the same
 * SHA256/base64url math regardless of which side of the exchange calls it.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7636
 */

/** Base64url-encodes to exactly a 43-char code_verifier — RFC 7636 §4.1's floor. */
const MIN_VERIFIER_BYTES = 32;
/** Base64url-encodes to exactly a 128-char code_verifier — RFC 7636 §4.1's ceiling. */
const MAX_VERIFIER_BYTES = 96;

/**
 * Base64url-encodes bytes with no padding (RFC 4648 §5), byte-for-byte
 * identical to Node's `Buffer.from(bytes).toString('base64url')` — but built
 * from `btoa`, which (unlike `Buffer`) exists in both Node and browsers.
 */
function toBase64Url(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 1) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/**
 * Derive a code_verifier from injected randomness (RFC 7636 §4.1 recommends
 * ≥32 octets). Randomness is injected so callers stay pure and testable —
 * this function performs no I/O and reads no ambient CSPRNG state itself.
 *
 * Base64url has no padding and its alphabet (`A-Za-z0-9-_`) is a strict
 * subset of RFC 7636's unreserved charset, so any output is automatically a
 * valid code_verifier as long as the byte count keeps the encoded length
 * within 43-128 chars — which is exactly what `MIN_VERIFIER_BYTES`..`MAX_VERIFIER_BYTES`
 * bounds below enforce. This function is now part of the SDK's public
 * surface (unlike the provider-side original, which only ever receives
 * internally-generated byte counts), so an external caller passing an
 * out-of-range length is rejected here rather than silently producing a
 * code_verifier a spec-compliant authorization server would reject.
 */
export function generateCodeVerifier(randomBytes: Uint8Array): string {
  if (randomBytes.length < MIN_VERIFIER_BYTES || randomBytes.length > MAX_VERIFIER_BYTES) {
    throw new RangeError(
      `generateCodeVerifier requires ${MIN_VERIFIER_BYTES}-${MAX_VERIFIER_BYTES} random bytes (encodes to a 43-128 char code_verifier per RFC 7636 §4.1); got ${randomBytes.length}.`,
    );
  }
  return toBase64Url(randomBytes);
}

/**
 * Derive the S256 code_challenge for a code_verifier:
 * BASE64URL(SHA256(ASCII(verifier))). Async because Web Crypto's
 * `subtle.digest` is Promise-based (unlike `node:crypto`'s synchronous
 * `createHash`) — the one API both Node and browsers actually share.
 */
export async function deriveCodeChallenge(verifier: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier));
  return toBase64Url(new Uint8Array(digest));
}
