import 'server-only';
import { headers } from 'next/headers';
import { NONCE_HEADER } from '@/middleware/security-headers';

/**
 * Read the per-request CSP nonce (generated by middleware, applied to
 * script-src) from the incoming request headers. `headers()` is itself a
 * Request-time API, so calling this opts the caller into dynamic rendering —
 * no separate `connection()` call is needed alongside it.
 *
 * Server Component only. Shared by every layout that needs the nonce (root
 * layout for its own inline scripts/ThemeProvider; dashboard layout for
 * threading it into Canvas's NonceProvider) so the read logic can't drift
 * between call sites.
 */
export async function getRequestNonce(): Promise<string | undefined> {
  const requestHeaders = await headers();
  return requestHeaders.get(NONCE_HEADER) ?? undefined;
}
