/**
 * dockerfile-synthesis-core — the pure decision half of D1's "a Dockerfile at
 * the root wins, else a default buildpack."
 *
 * "Buildpack" here is NOT an external buildpack system (no Cloud Native
 * Buildpacks, no `pack build`) — it is this module synthesizing a plain
 * Dockerfile for the two source shapes PageSpace can recognize on its own: a
 * Node app (a `package.json` at the root) and static content (an
 * `index.html` at the root with no `package.json`). Anything else is refused
 * — the caller is expected to surface that refusal BEFORE spending any work
 * snapshotting or uploading the source, per the founder's own framing: "tell
 * the user to add a Dockerfile," not silently fail deep in the build queue.
 *
 * Kept pure and fs-free on purpose (matching `provisioner-core.ts`/
 * `router-core.ts`'s split): the caller does the filesystem/sandbox I/O
 * (listing root entries, reading `package.json`) and this module only
 * decides. `materializeBuildSource` in the processor's
 * `app-build-runner.ts` still owns the actual "Dockerfile at root wins"
 * ENFORCEMENT (it throws if the materialized source has none) — this module
 * runs earlier, before that source even exists, so a Dockerfile is either
 * already there or gets synthesized in time to satisfy it.
 *
 * BOTH TEMPLATES TARGET `PUBLISHED_APP_INTERNAL_PORT`, not a stack's own
 * default. `buildMachineConfig` (`build-core.ts`) forwards that one fixed
 * port for every published app regardless of stack — a synthesized nginx
 * image left listening on its stock port 80 would build, push, and deploy
 * clean while being completely unreachable, since Fly only ever forwards to
 * the configured internal port.
 */

import { PUBLISHED_APP_INTERNAL_PORT } from './build-core';

/**
 * Stamped as the FIRST LINE of every synthesized Dockerfile. A Dockerfile
 * carrying this line is ours and safe to regenerate/overwrite on the next
 * publish (the source shape may have changed since); a Dockerfile WITHOUT it
 * is user-authored and must always win, per D1 — never regenerated over,
 * never even inspected further. This is what lets `use_existing` and
 * `synthesize` stay distinguishable across repeated publishes instead of a
 * once-generated file silently becoming permanently authoritative or a real
 * user Dockerfile being clobbered by a later publish.
 */
export const GENERATED_DOCKERFILE_MARKER =
  '# Generated by PageSpace publish — edits are yours; delete this line to stop regeneration';

export interface SourceRootListing {
  /**
   * `null` when there is no `Dockerfile` at the root. Otherwise the file's
   * OWN first line — the caller reads only that much, not the whole file —
   * compared against `GENERATED_DOCKERFILE_MARKER` to decide ownership.
   */
  dockerfileFirstLine: string | null;
  hasIndexHtml: boolean;
  /** `null` when there is no `package.json` at the root at all. */
  packageJson: { scripts?: Record<string, string>; main?: string } | null;
}

export type DockerfineSynthesisRefusalReason =
  | 'no_recognizable_source'
  | 'node_missing_start_command';

export type DockerfileSynthesisPlan =
  /** A Dockerfile is already at the root — D1 says it wins; nothing to synthesize. */
  | { action: 'use_existing' }
  | { action: 'synthesize'; dockerfile: string; dockerignore: string }
  | { action: 'refuse'; reason: DockerfineSynthesisRefusalReason };

// TODO(publish/dockerfile-synthesis): pin to the CURRENT node:20-alpine /
// nginx:alpine digest before this synthesizer ships live — this repo has no
// registry access at generation time, so these are placeholder digests
// (obviously fake: all-zero) rather than a fabricated value that would look
// real but isn't. A floating tag is not acceptable for a generated image
// definition: fully pin it before removing this TODO.
const NODE_IMAGE_TAG = 'node:20-alpine@sha256:0000000000000000000000000000000000000000000000000000000000000';
const NGINX_IMAGE_TAG = 'nginx:alpine@sha256:0000000000000000000000000000000000000000000000000000000000000';

const BASE_DOCKERIGNORE = `node_modules
.git
.env*
*.pem
id_*
`;

const NODE_DOCKERIGNORE = BASE_DOCKERIGNORE;
const STATIC_DOCKERIGNORE = BASE_DOCKERIGNORE;

function synthesizeNodeDockerfile(pkg: { scripts?: Record<string, string>; main?: string }): DockerfileSynthesisPlan {
  const startCommand = pkg.scripts?.start
    ? ['npm', 'run', 'start']
    : pkg.main
      ? ['node', pkg.main]
      : null;

  if (startCommand === null) {
    // Neither a `start` script nor a `main` entry — there is no command this
    // synthesizer can honestly hand to `CMD`, and guessing one (`index.js`?)
    // would produce a container that fails at run time instead of at publish
    // time, which is a worse place for the user to find out.
    return { action: 'refuse', reason: 'node_missing_start_command' };
  }

  const buildStep = pkg.scripts?.build ? '\nRUN npm run build' : '';
  const cmdJson = JSON.stringify(startCommand);

  // `PORT` is also set on the machine's env by `buildMachineConfig`, but that
  // only helps an app that reads `process.env.PORT` — setting it here too
  // costs nothing and makes the image correct even run outside a published
  // machine (e.g. `docker run -p 8080:8080` while debugging one locally).
  //
  // Non-root: `node` images ship an unprivileged `node` user (uid 1000) for
  // exactly this — a synthesized image should never run the user's app as
  // root inside the container.
  const dockerfile = `${GENERATED_DOCKERFILE_MARKER}
FROM ${NODE_IMAGE_TAG}
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .${buildStep}
RUN chown -R node:node /app
USER node
ENV PORT=${PUBLISHED_APP_INTERNAL_PORT}
EXPOSE ${PUBLISHED_APP_INTERNAL_PORT}
CMD ${cmdJson}
`;

  return { action: 'synthesize', dockerfile, dockerignore: NODE_DOCKERIGNORE };
}

function synthesizeStaticDockerfile(): DockerfileSynthesisPlan {
  // nginx's stock `default.conf` listens on 80, which a container running
  // this image never gets traffic on — Fly forwards only to
  // `PUBLISHED_APP_INTERNAL_PORT`. The stock conf is replaced outright rather
  // than patched with `sed` against `listen 80;`, whose exact spacing/IPv6
  // variants are an upstream implementation detail this shouldn't depend on.
  //
  // Non-root + unprivileged port, together: nginx's official image ships an
  // `nginx` user, but that user cannot bind port 80 (a privileged port) —
  // running as `nginx` therefore REQUIRES listening on an unprivileged port,
  // which `PUBLISHED_APP_INTERNAL_PORT` already is (Fly forwards to it
  // regardless of stack), so this costs nothing extra: the same rewrite that
  // makes the image reachable also makes running as non-root possible.
  const dockerfile = `${GENERATED_DOCKERFILE_MARKER}
FROM ${NGINX_IMAGE_TAG}
COPY . /usr/share/nginx/html
RUN printf 'server {\\n  listen ${PUBLISHED_APP_INTERNAL_PORT};\\n  root /usr/share/nginx/html;\\n  index index.html;\\n  location / {\\n    try_files \\$uri \\$uri/ /index.html;\\n  }\\n}\\n' > /etc/nginx/conf.d/default.conf \\
  && chown -R nginx:nginx /usr/share/nginx/html /var/cache/nginx /etc/nginx/conf.d \\
  && touch /var/run/nginx.pid && chown nginx:nginx /var/run/nginx.pid
USER nginx
EXPOSE ${PUBLISHED_APP_INTERNAL_PORT}
`;
  return { action: 'synthesize', dockerfile, dockerignore: STATIC_DOCKERIGNORE };
}

/**
 * Decide what, if anything, to synthesize for a snapshot's root.
 *
 * Order matters and is exactly D1's: an existing Dockerfile always wins —
 * checked first — UNLESS it is one we generated ourselves, identified by
 * `GENERATED_DOCKERFILE_MARKER` on its first line. A user-authored Dockerfile
 * (no marker) is `use_existing`, full stop, never inspected further — a repo
 * that happens to also have a `package.json` (e.g. tooling config, not the
 * app itself) must never have its real Dockerfile silently overridden by a
 * Node guess. A marker-carrying Dockerfile is OURS from a previous publish,
 * so it is safe (and correct) to fall through to regeneration: the source
 * shape may have changed since, and a stale generated file must never become
 * silently authoritative just because it happens to still be there.
 */
export function planDockerfileSynthesis(listing: SourceRootListing): DockerfileSynthesisPlan {
  if (listing.dockerfileFirstLine !== null && listing.dockerfileFirstLine !== GENERATED_DOCKERFILE_MARKER) {
    return { action: 'use_existing' };
  }
  if (listing.packageJson) return synthesizeNodeDockerfile(listing.packageJson);
  if (listing.hasIndexHtml) return synthesizeStaticDockerfile();
  // A marker-carrying Dockerfile with no recognizable source underneath it
  // (package.json/index.html both gone) has nothing to regenerate FROM —
  // `use_existing` keeps the last-known-good image definition rather than
  // refusing a publish that was working a moment ago.
  if (listing.dockerfileFirstLine === GENERATED_DOCKERFILE_MARKER) return { action: 'use_existing' };
  return { action: 'refuse', reason: 'no_recognizable_source' };
}
