name: Build Desktop App

# This workflow builds, signs, and publishes the desktop app
# electron-builder automatically creates draft releases on GitHub when GH_TOKEN is provided
# After the workflow completes, review and publish the draft release on GitHub

on:
  push:
    tags:
      - 'desktop-v*'  # Trigger on tags like desktop-v1.0.0
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: false
        default: '1.0.0'

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build desktop app TypeScript
        run: pnpm --filter desktop build

      - name: Import code signing certificate
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p actions build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions build.keychain
          rm certificate.p12

      - name: Debug notarization credentials
        run: |
          echo "Checking notarization environment variables..."
          if [ -z "$APPLE_ID" ]; then
            echo "ERROR: APPLE_ID is not set or empty"
          else
            echo "✓ APPLE_ID is set (length: ${#APPLE_ID})"
          fi

          if [ -z "$APPLE_APP_SPECIFIC_PASSWORD" ]; then
            echo "ERROR: APPLE_APP_SPECIFIC_PASSWORD is not set or empty"
          else
            echo "✓ APPLE_APP_SPECIFIC_PASSWORD is set (length: ${#APPLE_APP_SPECIFIC_PASSWORD})"
          fi

          if [ -z "$APPLE_TEAM_ID" ]; then
            echo "ERROR: APPLE_TEAM_ID is not set or empty"
          else
            echo "✓ APPLE_TEAM_ID is set: $APPLE_TEAM_ID"
          fi
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Package macOS app (signed and notarized)
        run: pnpm --filter desktop package:mac
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: |
            apps/desktop/dist-electron/*.dmg
            apps/desktop/dist-electron/*.zip
            apps/desktop/dist-electron/*.yml
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build desktop app TypeScript
        run: pnpm --filter desktop build

      - name: Package Windows app
        run: pnpm --filter desktop package:win
        env:
          CSC_LINK: ${{ secrets.WINDOWS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PWD }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: |
            apps/desktop/dist-electron/*.exe
            apps/desktop/dist-electron/*.yml
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build desktop app TypeScript
        run: pnpm --filter desktop build

      - name: Package Linux app
        run: pnpm --filter desktop package:linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            apps/desktop/dist-electron/*.AppImage
            apps/desktop/dist-electron/*.deb
            apps/desktop/dist-electron/*.rpm
            apps/desktop/dist-electron/*.yml
          retention-days: 30

  create-release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: always()  # Run even if Windows/Linux builds fail
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/macos-packages/*
            artifacts/windows-packages/*
            artifacts/linux-packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
